geany/geany-plugins

debugger/src/debug.c, scope/src/conterm.c
pty.h doesn't exist on OS X, it's contents is present in util.h. This fixes plugins compilation problem on OS X (I tried just the basic ones with minimal dependencies).
=> scope, debugger: use util.h instead of pty.h on OS X

build/geanylua.m4, geanylua/wscript_configure
Make sure the found Lua package is version 5.1 and not newer, as 5.2
breaks compilation.
The issue with 5.2 was reported by an user on IRC.
=> geanylua: Do not accept Lua5.2 as the plugin doesn't build with it

debugger/src/dbm_gdb.c
GDB 7.7 doesn't understand `&` as an argument to `-exec-run`.
Moreover, the code handling errors from GDB has an issue with this
error and leads to a crash.
Closes https://sourceforge.net/p/geany-plugins/bugs/112/
---
@cesspit Are you OK with this?  I think it's important to do something as it leads to a crash when using GDB 7.7 (version is according to your findings).  I also think that even if it prevents asynchronous debugging, it's still worth to fix until a proper asynchronous fix is released.
=> debugger: Fix crash with GDB 7.7

build/multiterm.m4
According to the documentation
http://www.gnu.org/software/automake/manual/html_node/Vala-Support.html
$VALAC contains 'valac' when valac was not found. I kept the empty
string test just in case it is returned under some special circumstances.
This fixes autogen on OS X.
=> Properly test valac existence

commander/README, geanygendoc/README, geanylatex/doc/geanylatex.html, geanylatex/doc/geanylatex.tex, geanylipsum/README, geanypg/README, geanypg/doc/geanypg.html, geanysendmail/README, git-changebar/README, multiterm/README, pohelper/README, tableconvert/README, treebrowser/README, updatechecker/README, webhelper/README
Apparently the old tracker URL doesn't work anymore, so use the new one.
=> Fix SourceForge tracker URL

pairtaghighlighter/src/pair_tag_highlighter.c
The second argument for SCI_INDICATORCLEARRANGE is the length to clear,
not the end position.
This used to work on earlier versions of Scintilla for some reason,
probably because it didn't check length, but current versions do nothing
with an invalid length.
=> pairtaghighlighter: Fix clearing previous indicators

projectorganizer/src/prjorg-main.c
The API version check was rolled back as part of c890cbc3 probably by
mistake, as the plugin really depends on 221 as it uses the new
TagManager API.
---
@techee is that OK?
=> projectorganizer: Fix API version check

build/debugger.m4, build/scope.m4, build/wafutils.py, debugger/src/debug.c, debugger/wscript_configure, scope/src/conterm.c, scope/wscript_configure
FreeBSD has openpty() in *libutil.h*.
I PR this because while the Waf changes work, they might be deemed ugly.  @eht16 if you have a better version for this it'd be welcome :)  Otherwise they are OK enough with me.
=> Fix checks for openpty() on FreeBSD

build/wafutils.py, overview/wscript_build, overview/wscript_configure
Fix build of the Overview plugin with Waf.  This fixes a few things in the overview's `wscript_build`, and adds a method to check for C99 compiler support.
Closes #220
=> overview: Fix Waf build

HACKING
Improve the section on Autotools, and add a basic section for Waf (not that I'm a expert on this one).
=> Extend docs on adding a plugin to the build systems

addons/src/ao_wrapwords.c, projectorganizer/src/prjorg-sidebar.c, tableconvert/src/tableconvert_ui.c
Fix actually translating some strings marked as translatable (in addons/wrapword and tableconvert).  Overview has a similar problem but I opened https://github.com/codebrainz/overview-plugin/pull/15 to please @codebrainz :)
Also, mark a few more visible strings as translatable.  This is harmless for the string freeze, as the strings weren't translatable at all anyway, so while they are technically new in the translations they aren't new in the code.  Maybe this could also warrant an update of the PO file as we are early in the freeze, so hopefully some translators will get the update version and the 6 additional strings.
=> Fix missing translations

addons/src/ao_openuri.c
Current word selection fails on URI's containing ~ and/or + (like launchpad PPA's). Adding ~ and + to GEANY_WORDCHARS fixes this.
=> addons: support for URI's containing ~ and +

automark/src/automark.c
`g_idle_add` does not make a big performance impact but improves usability
by removing annoying delay
=> Replace g_timeout_add with g_idle_add

geanyvc/src/externdiff.c
This fixes Windows cross-compilation on non-Windows systems with case-sensitive file systems.
Since most non-Windows systems use case-sensitive file systems and header files are usually named in lowercase, using lowercase header names in sources should be a good idea.
On Windows, it just doesn't matter.
Currently the Geany Windows nightly builds are broken because of 87e1f9fb8ae77cbd1ff3fe5c9769d15272ef1171.
=> Use lowercase header names

addons/src/ao_openuri.c
The double entree is indeed superfluous, took the added "_" out as recommended. Thanks for that. Looking good now :-)
=> fix double "_" entree in GEANY_WORDCHARS

README, build/common.m4
This allows to change the default for whether every plugins are enabled or disabled, effectively allowing to easily select either all, or only a specific set of plugins.
To force enable all plugins:
`configure --enable-all-plugins`
To force enable all plugins, but disable Addons:
`configure --enable-all-plugins --disable-addons`
To force enable all plugins, but Addons which is checked automatically:
`configure --enable-all-plugins --enable-addons=auto`
To disable all plugins, but force enable Addons:
`configure --disable-all-plugins --enable-addons`
=> autotools: Add a flag to enable or disable all plugins

debugger/src/dconfig.c, debugger/src/envtree.c
As the module is resident, the global variables won't get reinitialized
automatically when the plugin is reloaded, so reinitialize them
explicitly.
This is especially important for the `empty_row` variable as not
re-initializing it will lead to a double-free, and possibly a crash.
=> debugger: Fix internal EnvTree state after plugin reload

autoclose/src/autoclose.c
Translations tend to change the width of the text, and horizontal
scrolling in such a dialog is annoying.  So, let the size request do
its job for the width and don't allow horizontal scrolling.
@scriptum
=> autoclose: Don't scroll the preferences UI horizontally

overview/README
I didn't make this clear, only mentioned in the description of the original PR to add the plugin.
If many plugins were to do this, it could become a maintenance burden trying to keep track of where all changes should go to, and which files can be touched. Maybe we should leave this PR open as reminder to further investigate a better way to handle allowing external plugins to be combined into Geany-Plugins (after next release of course).
I won't forget for too long because it bites me every time someone touches files in `overview` in the fork :)
=> Overview: Update README from upstream

projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-sidebar.c
This is consistent with Geany and follows various common HIG.
https://developer.gnome.org/hig-book/stable/menus-design.html.en#menu-item-type-command
----
**WARNING**: do *not* merge before 1.25 is out, as we froze strings and this modifies some.
=> [1.26] projectorganizer: Add ellipsis to menu items requiring user input

addons/src/ao_doclist.c, build/addons.m4
This really fixes only compilation of the plugin and
makes the document list in the toolbar working.
There are still plenty of deprecation warnings across the whole
plugin and I don't know which to fix and which to accept, e.g.
GTK 3.10 deprecated stock items, some later version
deprecated the whole GtkStatusIcon.
=> Replace deprecated GTK2 API to fix compilation against GTK3

addons/src/ao_bookmarklist.c
Update bookmark list also on any line changes in the document
In addition to updating the bookmark list on document notebook tab change
and adding/removing line markers, also rebuild the bookmark list
when the text in the document changes with lines added or deleted.
Should fix SF bugs 129 and 39.
This implements some ideas mentioned in the above bug reports like updating the bookmark list
in an idle callback. Additionally, the list store is detach from the GtkTreeView to increase performance on big bookmark lists.
Maybe it is still worth to add a refresh button (or rather a context menu item to refresh) but I would try it without at first.
There is one issue left: if the `Transpose current line` feature is used, the bookmarks don't update. But this is not a problem in the plugin but …
=> Addons bookmark refresh fix

scope/src/debug.c
Reported by GCC's `-Wformat-security`.
=> scope: Don't use an untrusted string as a printf format

geanypy/m4/ax_python_library.m4
Try to pre-load the Python library with its real, fully dereferenced
path.
This is necessary because some installations don't have the symlink
from the generic (.so) to the versioned one (.so.X.Y) when the Python
development files aren't installed (i.e. libpython2.7-dev on Debian).
Fortunately for us (at least under Debian) Python has the name of the
final installed library in its `INSTSONAME` sysconfig's config var, so
use this instead of `LDLIBRARY` when it's available.
Closes https://github.com/codebrainz/geanypy/issues/20
=> geanypy: Try to locate the real dereferenced Python DSO

spellcheck/src/gui.c, spellcheck/src/gui.h, spellcheck/src/scplugin.c, spellcheck/src/scplugin.h
Add a new option to enable to show spelling suggestions directly in the
editor menu by not creating a dedicated sub menu.
To retain the previous behaviour, this option is disabled by default.
Closes #287.
=> Implement top-level spelling suggestions in editor menu (closes #287)

addons/README, addons/src/Makefile.am, addons/src/addons.c, addons/src/ao_copyfilepath.c, addons/src/ao_copyfilepath.h, addons/src/ao_wrapwords.c, addons/src/ao_wrapwords.h, po/POTFILES.in
This little addon allows the user to easily copy the current document's
full file path to the clipboard in order to use it elsewhere, e.g.
to paste it into a terminal or similar.
The addon provides a menu item in the Tools menu and a
new keybinding.
This is a feature I personally often wished and also got reports
from users who wish this feature.
There is no configuration as this feature is that trivial and small.
=> Addons: Add new feature "Copy File Path"

multiterm/src/Makefile.am, multiterm/src/config.vala, multiterm/src/context-menu.vala, multiterm/src/notebook.vala, multiterm/src/plugin.vala, multiterm/src/shell-config.vala, multiterm/src/tab-label.vala, multiterm/src/terminal.vala, multiterm/src/vapi/geany.vapi, multiterm/wscript_build, po/POTFILES.in
Closes #247.
---
I'm not quite sure whether https://github.com/geany/geany-plugins/blob/master/multiterm/src/shell-config.vala#L48 should be translated or not, but I left it alone.
Also, being able to translate the [default profile name](https://github.com/geany/geany-plugins/blob/master/multiterm/src/defconf.vala#L97) would be nice.  This would be quite easy if this was a real file that would get installed instead of a string template.  Or the template could be built with a translation in the middle.
=> Multiterm: make strings translatable

wscript
As Waf is to be dropped after the 1.26 release, inform the user
to better use the Autotools build system.
As suggested by @elextr in https://github.com/geany/geany/issues/679#issuecomment-148525367
=> Add a deprecation notice when using the Waf build system

build/geanyvc.m4, geanyvc/src/geanyvc.c
please merge the fixes for 1.26
=> Geanyvc fix

spellcheck/src/speller.c
Temporarily add ' (single quote) to WORDCHARS to be able to parse
whole words containing a single quote (like doesn't and similar in English).
Closes #320.
=> Improve detection of English contractions and other use of single quotes

geanynumberedbookmarks/src/geanynumberedbookmarks.c
Pass the document pointer instead of always getting the current document, which may or may not be the one we're working on.
Closes #301.
---
@peter-scholtens Could you please try this and see if it actually fixes the issue you've been having?
=> geanynumberedbookmarks: Pass document pointer around where needed

geanyctags/src/geanyctags.c
Add mnemonics to two labels in the Find Tag dialog that already have a mnemonic widget but no actual mnemonics.
Also, fix the match type labels to be translatable.
=> GeanyCtags: Find Tag dialog UI fixes

geanypy/m4/ax_python_devel.m4, geanypy/src/Makefile.am
This actually fixes building on Debian Unstable that ships
ax_python_devel.m4 in autoconf-archive, and apparently aclocal prefers
system directories.  So we get the system version, which happens to be
the latest, which changed API.
To avoid breaking older systems that would also ship ax_python_devel.m4
but in an older version with the older API, keep using the old API too.
=> geanypy: Update bundled ax_python_devel.m4 to latest upstream

projectorganizer/README, projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-sidebar.c
Do the same for ProjectOrganizer as for Geany in https://github.com/geany/geany/pull/582
=> projectorganizer: Use the word "symbol" instead of "tag"

geanyvc/src/geanyvc.c
Not tested, but looks straightforward, it's only straight API renames.
=> geanyvc: Drop use of the most obvious deprecated Geany API

addons/src/addons.c, addons/src/ao_openuri.c
Quickly tested, seems to work fine.
=> addons: Drop use of the most obvious deprecated Geany API

spellcheck/src/gui.c, spellcheck/src/scplugin.c, spellcheck/src/speller.c, spellcheck/src/speller.h
Should not introduce functional changes, mere code cleanup/improvement/change.
=> Spellcheck: Less deprecated stuff and various improvements on the way

projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-sidebar.c
Not thoroughly tested but should be quite straightforward
=> projectorganizer: Drop use of the most obvious deprecated Geany API

autoclose/src/Makefile.am, automark/src/Makefile.am, codenav/src/Makefile.am, debugger/src/Makefile.am, defineformat/src/Makefile.am, devhelp/src/Makefile.am, geanydoc/src/Makefile.am, geanyextrasel/src/Makefile.am, geanyinsertnum/src/Makefile.am, geanylatex/src/Makefile.am, geanylipsum/src/Makefile.am, geanylua/Makefile.am, geanymacro/src/Makefile.am, geanyminiscript/src/Makefile.am, geanynumberedbookmarks/src/Makefile.am, geanyprj/src/Makefile.am, geanysendmail/src/Makefile.am, geanyvc/src/Makefile.am, lineoperations/src/Makefile.am, markdown/src/Makefile.am, multiterm/src/Makefile.am, overview/overview/Makefile.am, pairtaghighlighter/src/Makefile.am, pretty-printer/src/Makefile.am, scope/src/Makefile.am, shiftcolumn/src/Makefile.am, tableconvert/src/Makefile.am, treebrowser/src/Makefile.am, xmlsnippets/src/Makefile.am
This helps to get proper log messages prefixed with the plugin name
in Geany's Help->Debug Messages view as well as on console
logging.
For some plugins this might be unnecessary if they don't use any `g_message()`, `g_warning()` or similar functions but `G_LOG_DOMAIN` is also used by `g_return_if_fail()` and friends.
Defining it for all plugins at least reduces the chance to miss some plugin, also for the future.
Omitted the plugins GeanyPy and GeanyPG where seperate PRs exist (#371 and #370).
=> Define G_LOG_DOMAIN for all plugins where it is missing

geanypg/src/Makefile.am, geanypg/src/decrypt_cb.c, geanypg/src/encrypt_cb.c, geanypg/src/geanypg.c, geanypg/src/pinentry.c, geanypg/src/sign_cb.c, geanypg/src/verify_aux.c
This makes logging and error reporting in the plugin more consistent
with other plugins and Geany.
Also set the G_LOG_DOMAIN for the plugin in order to have proper
log messages.
=> Use GLib error reporting/logging instead of fprintf()

devhelp/src/dhp-plugin.c, geanyctags/src/geanyctags.c, geanydoc/src/geanydoc.c, geanyextrasel/src/extrasel.c, geanyinsertnum/src/insertnum.c, geanylatex/src/geanylatex.c, geanylipsum/src/geanylipsum.c, geanymacro/src/geanymacro.c, geanyprj/src/geanyprj.c, geniuspaste/src/geniuspaste.c, overview/overview/overviewplugin.c, pretty-printer/src/PluginEntry.c, scope/src/scope.c, shiftcolumn/src/shiftcolumn.c
Fix "translatability" of several plugins, either overall (*GeanyCTags*, *DevHelp*, *GeanyMacro*, *Overview*), only the infos, and remove redundant localization init in some plugins.
Symptoms are that translation might not work in certain cases i.e. if the plugin is loaded first (or alone), or only one from GP installed.
*GeanyPy* also suffers from the non-translatability, but it doesn't have `LOCALEDIR` and `GETTEXT_PACKAGE`properly set from it's build system so it's not as straightforward to fix. @codebrainz
=> Translatability of several plugins

geanypy/src/Makefile.am
This turns messages like:
```
** INFO: User plugins: /home/enrico/tmp/geany_conf/plugins/geanypy/plugins
** INFO: System plugins: /home/enrico/apps/share/geany/geanypy/plugins
```
into
```
GeanyPy-INFO: User plugins: /home/enrico/tmp/geany_conf/plugins/geanypy/plugins
GeanyPy-INFO: System plugins: /home/enrico/apps/share/geany/geanypy/plugins
```
=> Set G_LOG_DOMAIN for proper GLib error reporting/logging

geanyvc/src/geanyvc.c
This fixes a little regression which caused the VC menu item in the
top menubar to be placed after the Help menu item and not
before as it used to do.
See more discussion in https://github.com/geany/geany-plugins/commit/c6a7968d5ab71961db4b0a5e721d378048e60119#commitcomment-16518850
=> Use gtk_menu_shell_insert() to add the VC menu item to the menubar

geanyctags/src/geanyctags.c
Since the new spawn API, which is used by utils_spawn_sync() as well,
passing a whole command line in argv[0] doesn't work any longer.
So use the new spawn API directly which conveniently offers to
pass the command either as command line or as argv.
Tested on Linux and Windows.
I bumped the required API version. It seems unfortunately we didn't bump the API version in Geany when merging the spawn API but the currently used 226 is newer than the spawn API and is already available in the last Geany release, so it should be ok.
=> Use new spawn API to fix broken Win32 ctags.exe command execution

po/POTFILES.in, po/POTFILES.skip
Fixes `make check` when MultiTerm is not enabled.
Closes #390.
=> Skip auto-generated C sources from translation setup

spellcheck/src/gui.c, spellcheck/src/scplugin.c, spellcheck/src/speller.c
Apparently some older versions of cppcheck get stupid when passed extra
flags like `-D`, so try and make them happy by showing them those are
library (system-wide) headers rather than application (local) ones.
=> spellcheck: Use <> to include Geany headers

lineoperations/src/linefunctions.c
`new_file` is [assigned again with the return value of `g_strjoinv()`](https://github.com/geany/geany-plugins/pull/391/files#diff-12783b0a2f2a5a415ec6f2505c90e634R315), thus leaking the previous value.
=> lineoperations: Fix a memory leak found by cppcheck

codenav/src/utils.c, shiftcolumn/src/shiftcolumn.c
Introduced my legacy inclusion removal in 25e3c8851a5113423ce16a6b8008.
=> Fix implicit function declarations by including appropriate headers

debugger/src/tests/gdb_mi_test.sh
Don't rely on the test driver to create the subdirectory where we want
to write the tests temporary output to in `$builddir`.
Fixes tests under Ubuntu 12.04.
---
* before: https://travis-ci.org/b4n/geany-plugins/builds/114352090#L3722
* after: https://travis-ci.org/b4n/geany-plugins/builds/114358044#L3721
=> debugger: Don't rely on an Automake test driver implementation detail

.travis.yml
Would replace #172, which see also.
This is a new shot at enabling Travis CI on Geany-Plugins.  This time, it uses the new-style infrastructure which enables caching and is quite faster to start up.
* Pros:
* Faster to start up
* Has cache support
* We can build Geany and cache the result, meaning we can rebuild it only when it has changed.  This makes me think its better than using nightly *.deb*s, as we have the real latest version in all cases, and zero OS package compatibility issue.
* *ccache* support, meaning faster rebuilds
* Cons:
* No sudo, which means:
* We need their approval for new packages.  We currently miss:
this can however probably be addressed by using they approval procedure for those packages.  If we chose this version, I'll submit the requests there.
* No 3rd party …
=> Enable Travis CI v2

treebrowser/src/treebrowser.c
Not tested but pretty straightforward
=> treebrowser: Drop use of the most obvious deprecated Geany API

geanypy/src/geanypy-plugin.c
Have to add ~/.config/geany/plugins to Python's path otherwise loading plugins from there
fails.
Tested with a relatively complex plugin which also ships extra modules in subdirectory:
https://github.com/sagarchalise/geanypy-reStructured-preview
=> geanypy: fix loading plugins from user config directory.

.travis.yml
Show the actual commands Make runs instead of a pretty message, which while very cute is a lot less informative in case of error.
May help debugging https://travis-ci.org/geany/geany-plugins/jobs/115259916 (although it looks more like a very weird race condition than an actual issue)
=> travis: Make the build more verbose

build/gtk-bundle-from-msys2.sh
This is a helper script to easily fetch and extract plugin dependencies
on Windows using the MSYS2 environment.
Inspired and based on @kugel- 's initial script in https://github.com/geany/geany/pull/560.
Currently it installs the dependencies we had already in the past (enchant, lua, libgit2, libsoup, ctpl, libxml2) and a few new ones which we got for free from MSYS2 (webkitgtk, ctags, gnupg/gpgme).
This script works like the one from Geany but only extracts additional dependencies to be merged into the bundle created for Geany.
=> Add shell script to add plugin dependencies into GTK bundle on MSYS2

build/common.m4, build/vars.build.mk
And remove unused define PKGLIBDIR and quote paths even.
As continuation of #374 after more testing on Windows.
These should be last bits regarding Waf->Autotools migration for G-P on Windows, so I hope.
As we all know, I'm not an Autotools expert: maybe there is a better way/location to overwrite `docdir` than in `GP_CHECK_MINGW`.
=> Set docdir on Windows builds

geniuspaste/src/geniuspaste.c
This workarounds a strange crash on Windows when the default GTK
URL handler is called.
We need the URL handler only on the secondary text label but we
cannot access it directly, so iterate over all labels of the message
dialog's message area and attach the custom handler to all of the
labels. This shouldn't harm much as only the secondary label contains
a link.
Here is the gdb backtrace from running on Windows:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x61a3ca04 in ?? () from H:\all\bin\libgtk-win32-2.0-0.dll
(gdb) bt
#0  0x61a3ca04 in ?? () from H:\all\bin\libgtk-win32-2.0-0.dll
#1  0x61a4f96c in ?? () from H:\all\bin\libgtk-win32-2.0-0.dll
#2  0x63c45fd2 in ?? () from H:\all\bin\libgobject-2.0-0.dll
#3  0x63c57c26 in ?? () from H:\all\bin\libgobject-2.0-0.dll
#4 …
```
=> Geniuspaste: Install a custom URL handler for Paste link

geanygendoc/docs/Makefile.am
Apparently rst2html 0.8.1 from Ubuntu 12.04 incorrectly resolves
relative paths to the stylesheets listed in `--stylesheet-path` but the
first one.
Work around this by providing absolute paths to the stylesheets.
---
Should fix the intermittent Travis failures we have.  I still don't know why sometimes that target is built (it shouldn't, as it's up2date -- maybe the buildbot has an incorrect system date?), but at least with this fix building it succeeds.
=> geanygendoc: Work around an rst2html 0.8.1 bug

debugger/src/vtree.c
on_key_pressed() is an existing callback function so the pointer is
always non-NULL:
vtree.c:164:14: warning: comparison of function 'on_key_pressed' not equal to a null pointer is
always true [-Wtautological-pointer-compare]
if (NULL != on_key_pressed)
~~~~    ^~~~~~~~~~~~~~
Remove the unnecessary check.
=> debugger: eliminate llvm warning

geanypy/src/geanypy.h
Copy fix for Scintilla macro name clash with geanypy
=> Copy fix from upstream

xmlsnippets/src/plugin.c
=> xmlsnippets: Drop use of the most obvious deprecated Geany API

geanyinsertnum/src/insertnum.c
Not really tested, but should not be a big deal as it's only `s/ui_widget_set_tooltip_text/gtk_widget_set_tooltip_text/`, which are synonyms nowadays.
=> geanyinsertnum: Drop use of the most obvious deprecated Geany API

geanyminiscript/src/gms.c
=> geanyminiscript: Drop use of the most obvious deprecated Geany API

geanyprj/src/geanyprj.c, geanyprj/src/menu.c
=> geanyprj: Drop use of the most obvious deprecated Geany API

geanypy/src/geanypy-document.c, geanypy/src/geanypy-uiutils.c
Also introduce the Document.reload_force() alias to Document.reload_file(), as per non-deprecated Geany API.
@codebrainz @elextr
=> geanypy: Drop use of the most obvious deprecated Geany API

shiftcolumn/src/shiftcolumn.c
Quickly tested.
Rectangular selection handling is still broken, but nothing different than before the patches.
=> Shiftcolumn: Geany deprecation fixes + a simple fix

projectorganizer/src/prjorg-main.c, projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-project.h
There is a problem when there are multiple tabs added by plugins: if
on_project_dialog_open() is called and Project Organizer stores
the index of the tab and then another plugin adds a tab before the
Project Organizer's tab, then the stored index becomes invalid which
can lead to not correctly removing the tab from the dialog.
Instead store a pointer of the added tab widget and remove the widget
when the properties dialog is closed.
Fixes #444
=> projectorganizer: Fix multiple tabs in Project Properties

addons/src/ao_tasks.c
- Do not extract tokens from non-comments
- Strip the comment closing sequence from the text  
Allows to use `/* TODO: some stuff */` without the extra `*/` being in the tasks list
=> addons/tasks: Small improvments

pairtaghighlighter/src/pair_tag_highlighter.c
=> pairtaghighlighter: Fix crash if the tag name is missing

scope/src/utils.c
The brackets are apparently wrong - the check that should happen is
strcmp(text, "2147483648") < 0
but instead the whole expression
(s - text == 10 && strcmp(text, "2147483648"))
is compared if it's less than zero.
Noticed by LLVM:
```
utils.c:654:50: warning: comparison of constant 0 with boolean expression is always false
[-Wtautological-constant-out-of-range-compare]
(s - text == 10 && strcmp(text, "2147483648")) < 0) ? text : NULL;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
```
=> scope: Fix validate_number()

build/scope.m4
On Windows Scope doesn't need neither VTE nor pty.h, so drop the incorrect checks there.
=> scope: Fix dependencies checks on Windows

debugger/src/dbm_gdb.c
GDB doesn't like octal escape sequences in executable path passed to
`-file-exec-and-symbols`, yet it accepts them (but doesn't require
them) in arguments to `-break-insert`.
So, use an escaping valid everywhere, as for the moment it's unclear
whether there is any benefit to escaping special bytes in argument to
`-break-insert`, and so consistency is better.
Fixes #416.
=> debugger: Fix escaping target executable path if it contains non-ASCII

MAINTAINERS
Operation of Geany Plugins is untenable, commits are made without maintainer approval. The plugin has now diverged from upstream.
=> Resign Maintainership

git-changebar/README
The feature is non-obvious. It would probably take me quite a while to discover it if I hadn’t decided to go browse the code.
=> Git-Changebar: Mention the tooltip feature in the README

treebrowser/src/treebrowser.c
=> Fix typo in config key name "open_new_files"

addons/src/addons.c, addons/src/ao_markword.c, addons/src/ao_markword.h
For this to work, we need to connect to the "button-press-event" for
each document and then differentiate between single and double
clicks, using a timeout handler which is triggered first after the GTK
double-click-time has passed, i.e. GTK won't recognise the event as part
of a double click.
I didn't find a easier solution to differentiate between single and double click.
Better ideas are welcome.
Closes #445.
=> Addons: Implement deselect with single click

spellcheck/src/speller.c
Skipping quotes on word stripping should not be necessary any longer
since we add the single quote character to the wordchars list
(eaad256).
Fixes #484.
=> Strip single quotes from words' beginning and end

markdown/src/plugin.c, markdown/src/viewer.c, markdown/src/viewer.h
Add a Tools menu item "Export Markdown as HTML" to allow saving of the rendered HTML to disk instead of just the live preview.
Closes #497
=> Markdown: Allow exporting Markdown as HTML

build/i18n.m4
Testing files installed into /usr/share/locale/ with different values of environment variable LINGUAS:
```
LINGUAS="en_GB en"
None
LINGUAS="en_GB en es"
/usr/share/locale/es/LC_MESSAGES/geany-plugins.mo
LINGUAS undefined
/usr/share/locale/be/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/ca/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/da/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/de/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/es/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/fr/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/gl/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/it/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/ja/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/kk/LC_MESSAGES/geany-plugins.mo
/usr/share/locale/nl/LC_MESSAGES/geany-plugins.mo …
```
=> Fix build failure if no translation matching LINGUAS

treebrowser/src/treebrowser.c
Because it's not freed.
Also, why not just use the value passed to the function instead?
=> treebrowser: Free `renderers` in `on_treeview_renamed()`.

commander/src/commander-plugin.c
Latest GTK3 seems to emit notify::text when getting packed in a container, in response to layout-changed.  Thus, we need not to connect handlers relying on not-yet-valid pointers.  Fix that by connecting to signals after everything is properly set up.
=> commander: Fix crash on startup with latest GTK3

geanylua/glspi_sci.c
When not defining `INCLUDE_DEPRECATED_FEATURES`, unprefixed structure names are not available anymore.  Thus, use prefixed names.
---
Since the last Scintilla update in Geany (3.7.1) unprefixed structure names are hidden.  This is good in theory, and will avoid thinks like 87d4bbcd16a41fce93b7da20c2135ff728b25791 in the future, but GeanyLua used unprefixed names.
So, in addition to the fix, do we want to restore the old names, or break API to reflect those are now removed, or do we consider it's not part of our API and thus don't care?  Of course as it's a structure name, it only affects building the code, the generated one is still binary compatible anyway.
@elextr @codebrainz @frlan
=> geanylua: Fix build with latest Scintilla

debugger/src/dbm_gdb.c
The debug-output is accessing err. If err is Null, it will fail most likely.
=> Debugger: Move debug output accessing after check whether err != Null

spellcheck/src/speller.c
We remove the underscore character temporarily from the wordchars
to make Scintilla split words on underscore.
After splitting the current line into words, we add the underscore again
to the document's wordchars setting if it was in before.
Fixes #496.
=> Treat underscore as word seperator

geanydoc/src/geanydoc.c
This makes the plugin more useful for namespaced languages like Python, where you often want to tweak the words a bit (e.g. `xyzzy` → `somelib.xyzzy`) before looking them up.
=> geanydoc: Current word as initial text in interactive mode

treebrowser/src/treebrowser.c
This menu has many useful items (I use at least 6 of them daily), but finding them manually with Up/Down or the mouse is annoying.
The choice of mnemonics is somewhat arbitrary, but they are unique.
Note that TreeBrowser has keybindings for a few of these operations, but they are not quite the same thing, because keybindings are global to Geany, and the global keybinding space is sort of crowded for me already (hard to pick a convenient but unused one).
=> TreeBrowser: more mnemonics in the context menu

treebrowser/src/treebrowser.c
GTK+ by default maps Shift+F10 to the same thing as Menu, which is useful for laptop keyboards (that have no Menu key). But because TreeBrowser handles keypresses on its own, it doesn't get this functionality automatically.
Implementation is per the "Test for modifier keys correctly" section of the GTK+ reference manual.
=> TreeBrowser: pop up context menu on Shift+F10

geanyctags/src/geanyctags.c, projectorganizer/src/prjorg-main.c
This avoids platform-specific paths to the documentation and the html formating is also nicer.
=> Use online version of plugin help

treebrowser/src/treebrowser.c
TreeBrowser has a "Follow current document" option, but I don't use it because it causes the tree's root to change. Still, sometimes I have a large tree and I want to quickly find the current document in it.
=> TreeBrowser: keybinding to track current file

treebrowser/src/treebrowser.c
This fixes a bug that could be reproduced as follows:
1. ensure that *no* item in the tree is selected (highlighted);
2. press the "Refresh" keybinding.
Without this fix, the contents of the tree are duplicated.
=> TreeBrowser: fix refreshing without selection

.travis.yml
While in general one should avoid returning big structs for performance
reasons, it's no big problem for small structs and it can lead to more
readable code.
Having this check on for everything seems to be too strict - if someone
is returning big structs like crazy, someone will probably notice during
the review. Otherwise it's no problem.
=> Remove -Werror=aggregate-return from travis flags

geanypy/geany/Makefile.am, geanypy/geany/__init__.py, geanypy/geany/logger.py, geanypy/geany/plugin.py, geanypy/src/Makefile.am, geanypy/src/geanypy-app.c, geanypy/src/geanypy-document.c, geanypy/src/geanypy-editor.c, geanypy/src/geanypy-glog.c, geanypy/src/geanypy-plugin.c, geanypy/src/makefile.win32
=> Sync with latest upstream

treebrowser/src/treebrowser.c
This behavior might be unwanted when changing project settings which
is unrelated to project base path and also fixes filebrowser behavior
with the updated way project-save signal is emitted.
Merging should wait until how the discussion in https://github.com/geany/geany/pull/1400 evolves.
=> treebrowser: Don't change directory on project save

lineoperations/src/lineoperations.c
This shall ensure we don't access doc before checking it against NULL. also it stops cppcheck from failing.
=> Add additional checks for doc != NULL and removing such ones later

build/updatechecker.m4, updatechecker/README, updatechecker/src/updatechecker.c
This should fix deprecated warnings on more recent soup versions.
=> Updatechecker: remove deprecated soup call

projectorganizer/src/prjorg-sidebar.c
Since expand_on_idle() is called as an idle function, it can happen it's
executed after project is closed in which case it should just return
without accessing variables with invalid values.
Should fix crash reported in #549.
=> projectorganizer: Make sure project is open before trying to expand the tree

README
This PR adds the travis status icon to README. I do like it but this might leak information about our users to travis while loading the image e.g. during browsing README.
=> Add travis status to README

projectorganizer/src/prjorg-sidebar.c
Well, yeah, there was a NULL check missing in the previous pull request. No make it clear what has changed I kept the previous patch and added another patch which fixes the crash when no project is open.
=> Fix crash in projectorganizer's crash-fix

addons/src/addons.c, addons/src/ao_markword.c, addons/src/ao_markword.h
This broke in 26e6906ed5eeab0adf5c7ad0ea177f99a3e49ea5, before the
Addons' feature "Mark Word" was enabled for all documents but after
changing the trigger to button-press-event, we connected the signal only
on "document-open" not on "document-new".
Fixes #562.
=> Enable Mark Word also for newly opened documents

geanydoc/src/geanydoc.c, geanyextrasel/src/extrasel.c, geanyinsertnum/src/insertnum.c, geanylua/glspi_ver.h, geanypg/src/geanypg.c, geanyprj/src/geanyprj.c, geanyvc/src/geanyvc.c, pretty-printer/src/PluginEntry.c, scope/src/scope.c, shiftcolumn/src/shiftcolumn.c, treebrowser/src/treebrowser.c
This is based on MAINTAINERS file. 
Idea is, to show enduser that the plugin might need its help.
=> Add note to plugins which are currently not actively maintained

geanygendoc/src/ggd-utils.c, geniuspaste/src/geniuspaste.c, git-changebar/src/gcb-plugin.c, overview/overview/overviewprefspanel.c, pohelper/src/gph-plugin.c, scope/src/scope.c
These patches try to fix the problems described in https://github.com/geany/geany-plugins/issues/507 for various plugins. They address only "serious" issues which prevent correct operation of the plugin like not locating .glade or .ui files, not "minor" problems like not showing documentation when clicking the Help button of the plugin.
There's the same function get_data_dir_path() in each plugin which locates the file in the correct directory for each platform. For OS X laucher script I added an environment variable GEANY_PLUGINS_SHARE_PATH which is set before the binary is started so it should be defined and can be used by the plugin.
=> Use paths relative to the bundle on OS X

geanydoc/src/geanydoc.c
With this change, pressing Enter in Geanydoc’s interactive dialog activates the OK button.
=> geanydoc: Make OK the default button in interactive mode

scope/src/debug.c
On failure to run gdb, Scope displays only the generic error message, such as "The system cannot find the file specified", giving the impression that the executable to be debugged is missing or has some other problem. This patch changes the message to "<gdb name>: <error>", for example "gdb: The system cannot find the file specified" (unlikely under *nix, but gdb may be missing from the PATH under Windows).
Closes https://github.com/geany/geany-plugins/issues/337
=> Improve the error message on attempt to run gdb

git-changebar/src/gcb-plugin.c
This fixes #567 for me, but I haven’t investigated exactly why this extra pixel is necessary, so I may be doing something wrong.
=> git-changebar: Fix spurious line wrapping

geanylua/glspi_app.c, geanymacro/src/geanymacro.c, geanynumberedbookmarks/src/geanynumberedbookmarks.c
This fixes crashes and critial warnings.
Fixes #585.
On Windows passing NULL as GdkKeymap crashed Geany, on other platforms there were "only" CRITICALs but possibly it could crash Geany there as well.
Using `gdk_keymap_get_default()` should suffice to use a valid GdkKeymap.
=> Pass a GdkKeymap to gdk_keymap_* functions

addons/src/ao_tasks.c, autoclose/src/autoclose.c, commander/src/commander-plugin.c, geanyextrasel/src/extrasel.c, geanygendoc/src/ggd-tag-utils.c, geanylatex/src/geanylatex.c, geanylua/glspi_doc.c, git-changebar/src/gcb-plugin.c, keyrecord/src/keyrecord.c, overview/overview/overviewui.c, projectorganizer/src/prjorg-main.c, projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-utils.c, scope/src/scope.c, scope/src/utils.c, spellcheck/src/gui.c
It seems newer cppcheck versions are too sensible to uninitialized loop
variables when the loop is created by a macro.
This might be a bug in cppcheck or it just cannot check the loop
properly. By initializing the affected variables explicitly, cppcheck
is happy while the unnecessary initialization should not have any
impacts.
The nightly builds for Debian Unstable are currently broken because of this.
=> Initialize loop variables to make cppcheck happy

.travis.yml
Test to fix Travis, do not merge unless Travis passes
=> Update travis to system with c++11 compiler

git-changebar/README, git-changebar/src/gcb-plugin.c
The patch adds a new keybinding action for undoing hunks. When cursor is
placed at a line with a diff and the keybinding is invoked, the
corresponding hunk is undone.
To get the previous contents at the given position, a temporary Scintilla
instance is used into which the previous state of the document is loaded
and the corresponding text from the previous state of the document is
extracted. This temporary Scintilla object is then destroyed.
=> git-changebar: Add the possibility to undo hunk at cursor position

workbench/src/sidebar.c, workbench/src/utils.c, workbench/src/wb_project.c
For details about the uninitialized variables and why thise broke `make check` (and so the nightly builds,  http://nightly.geany.org/) see https://github.com/geany/geany-plugins/pull/590.
The other commit is just to replace the deprecated `tm_get_real_path` calls.
=> Workbench: cppcheck initialize loop vars

projectorganizer/src/prjorg-project.c
At the moment the directory isn't closed when tm_get_real_path() returns
NULL or when the given path was already visited (happens e.g. with
symlink loops).
=> projectorganizer: Close dir created with g_dir_open() in some special cases

projectorganizer/src/prjorg-project.c
=> projectorganizer: Replace deprecated tm_get_real_path().

workbench/src/plugin_main.c
=> workbench: Increased required geany API version to 235 for usage of 'utils_get_real_path'.

geanylua/glspi_ver.h
=> geanylua: Increased required geany API version to 235 for usage of 'utils_get_real_path'.

workbench/README
The following things have been changed in the README file:
- updated sections "Downloads" and "Development Code"
- corrected section "Enabling the plugin":
The workbench menu is now placed inside the "Tools" menu.
- use definition lists instead of bulleted lists to describe the menu items.
This makes the text more readable and also fixes errors in the ReStructuredText format.
=> workbench: correct/update README.

scope/src/scope.c
This change adds tooltips to the existing scope toolbar buttons.
The texts for the tooltips are taken from the existing menu item labels.
=> scope: added tooltips to toolbar buttons.

addons/src/addons.c, addons/src/ao_markword.c, addons/src/ao_markword.h
Not sure if desired or not, but the marked results currently do not clear when the selected text is modified/deleted. The modification detects the deletion and clears the markers. Only works when single-click deselect is enabled.
=> addons/markword: Deselect when the selection changes

scope/src/program.c
Fixes #304.
For your convenience a PR with the fix as suggested by @J-Dunn. Tested on Ubuntu 16.04.
=> scope: only allow selection of folders for "working dir".

workbench/src/wb_project.c
On re-scan of a directory the tm tags for all directories of that project
were re-generated. This caused a crash. The crash only occured if the project
had more than one directory.
Now, only the tm tags of the selected/re-scanned project are re-generated.
Fixes #629.
=> workbench: on re-scan dir only regenerate tags for that dir, not for all.

geniuspaste/data/pastebin.geany.org.conf
Nothing critical but probably won't hurt.
=> Geniuspaste: Enable HTTPS for pastebin.geany.org

scope/src/Makefile.am, scope/src/store/scptreestore.c
Closes #398.
This reverts the makefile change from #397 and applies the change suggested by @b4n. There is no maintainer for scope right now and so I thought just let's do the change and we can close #398 so that it does not stay open forever.
=> scope: code re-factoring to prevent false positive from cppcheck.

treebrowser/src/treebrowser.c
Before this change, the treebrowser used an inconsistent mix of
capitalized and uncapitalized words in the context menu.  This
changes them to all be capitalized for consistency with other
GTK applications.
=> treebrowser: Use consistent capitalization in menu

addons/src/ao_markword.c
If the plugin gets activated *after* Geany has been started already,
we need to iterate all open documents and attach the "button-press"
signal handler.
Fixes #638.
=> Connect button-press signal handlers on plugin activation

projectorganizer/src/prjorg-menu.c, xmlsnippets/src/Makefile.am, xmlsnippets/src/tests.c
Is 26fd7328cd409ceb16557a0fe637d5c028c0598f enough for properly enabling the test program on `make check`? To me it seems, it was just missing or was it intentional that the test program isn't run on `make check`?
=> Fix cppcheck warnings

geanyvc/src/geanyvc.c
When the commit dialog is resized manually by the user, remember the chosen dimensions between commit dialog instances and sessions.
For me, the default size of 700x500 is often too small and so I resize the dialog on almost every commit I do. With this change, the last widget size is remember and re-applied.
=> GeanyVC: Remember the commit dialog size

build/spellcheck.m4, spellcheck/README, spellcheck/src/Makefile.am, spellcheck/src/scplugin.c, spellcheck/src/speller.c
Enchant 2.0 dropped some deprecated API and especially introduced
setting custom config/dictionary paths via an environment variable.
So, handle the API differences between Enchant 1.3, 1.5 and 2.0 and
document the changed custom dictionary behavior with 2.0 and later.
=> SpellCheck: Support Enchant 2.0 and later

geanylua/docs/geanylua-ref.html, geanylua/glspi_doc.c
It's continuation of the discussion #646 . Code example:
```lua
local s = geany.selection();
if (s ~= "") and (s ~= nil) then
local t = geany.fileinfo();
geany.newfile("", t.type);
geany.selection(s);
end
```
Old/current scripts don't need to be updated, they will still work!
=> GeanyLua: Add filetype to set in geany.newfile()

geanylua/examples/edit/right-trim.lua
Now script works with files with CRLF too (and with CR only). ```right-trim.lua ``` is presented as example (_geanylua/**examples**/edit/right-trim.lua_), but very useful (IMHO :)).
=> GeanyLua: Fix right-trim.lua

treebrowser/src/treebrowser.c
If 'gtk_icon_theme_lookup_by_gicon()' returns NULL then try again with icon "text-x-generic".
Fixes #657.
=> treebrowser: fallback to "text-x-generic" icon if info lookup fails.

addons/src/Makefile.am, addons/src/addons.c, addons/src/ao_colortip.c, addons/src/ao_colortip.h
This new feature shows a color tip if the mouse is hovered over a color value like e.g. #fff or #ffffff. If a color value is double clicked, then the Color Chooser is started. Both (showing the color tip and starting the Color Chooser) can be enabled and disabled via the plugin preferences. See #663.
I hope it can be added to the AddOns plugin as I think it's not worth writing a new complete own plugin for it.
=> addons: show color tip and start Color Chooser with double click 

pretty-printer/src/PluginEntry.c
Curretly PrettyprintXML can be used files only,
this pr changes that to
-  selection based prettty print if selection is valid XML
- Donot change doctype to XML if HTML
- use of plugin API functions when taking buffer text
P.S. Sorry about all the merge commits.
=> Prettyprint usage

MAINTAINERS
Have the maintainers github user name recorded somewhere so they can be pinged by users rather than waiting for them to notice an issue for their plugin was posted.
I have filled in the ones I know for sure, to everybody else, no offense, I am working from memory.
=> Add github names to maintainers file

utils/src/filelist.c, utils/src/filelist.h, workbench/README, workbench/src/dialogs.c, workbench/src/dialogs.h, workbench/src/plugin_main.c, workbench/src/popup_menu.c, workbench/src/sidebar.c, workbench/src/wb_project.c
The user can now select from two new context menu items to either create a new file or a new directory on the current selected position in the file tree. See #660.
This PR also includes a new function for the utils lib which is required for the new functionality in the workbench plugin.
=> workbench: added "Create file here..."/"Create directory here..."

po/fr.po, scope/data/scope.glade, scope/src/break.c, scope/src/debug.c, scope/src/inspect.c, scope/src/memory.c, scope/src/menu.c, scope/src/parse.c, scope/src/plugme.c, scope/src/prefs.c, scope/src/program.c, scope/src/scope.c, scope/src/thread.c, scope/src/utils.c, scope/src/views.c
* Fix several issues in the Scope plugin translation setup that led to a few strings not being extracted, and several translations not to be used.
* Yes, this "adds" new strings (column titles), but they were already there, just not translatable at all.
* Update the French translation after these fixes.
=> French translation update (and translation setup fixes for the Scope plugin)

workbench/src/wb_project.c
The key "Bookmarks" can be missing and that is not an error. So pass "NULL" for
parameter "error" on calling ```g_key_file_get_string_list()```. This prevents multiple
error messages from being written to one ```GErrror``` and so causing a GLib warning in
the debug messages. Fixes #714.
=> workbench: pass error=NULL to "g_key_file_get_string_list()" for key "Bookmarks"

utils/src/filelist.c, utils/src/filelist.h
This adds a new function to the utils lib which checks if a filepath matches the given file patterns.
This is a prerequisite for PR #695.
=> utils: added new function "gp_filelist_filepath_matches_patterns()".

workbench/README, workbench/src/Makefile.am, workbench/src/dialogs.c, workbench/src/menu.c, workbench/src/plugin_main.c, workbench/src/popup_menu.c, workbench/src/sidebar.c, workbench/src/sidebar.h, workbench/src/wb_monitor.c, workbench/src/wb_monitor.h, workbench/src/wb_project.c, workbench/src/wb_project.h, workbench/src/workbench.c, workbench/src/workbench.h
With this PR the workbench file list and sidebar will automatically be updated if a file is created, removed or renamed. The feature uses the file monitoring from the GIO lib to monitor directories. If required, the feature can be disabled in the workbench settings dialog.
This requires PR #694.
=> workbench: support live update. Closes #659.

workbench/src/wb_project.c, workbench/src/wb_project.h, workbench/src/workbench.c
Import the base path on adding a project by calling "wb_project_load()".
This prevents the user from having to close and re-open the workbench
once to have the base path imported. Fixes #709.
=> workbench: import base path on "Add project..."

build/workbench.m4, workbench/src/dialogs.c, workbench/src/wb_monitor.c, workbench/src/wb_monitor.h, workbench/src/wb_project.c, workbench/src/workbench.c
This hopefully fixes some Travis CI problems.
If GIO is not available and the GLib version is older than 2.46 then the feature "Live Update" will be disabled. Everything else works normal. In the "Settings"-Dialog the option do enable/disable the feature is grayed out and the tooltip text for the option informs the user that the feature is not available on the system.
=> workbench: make "live update"-feature depending on GIO and Glib version 2.46

workbench/src/popup_menu.c, workbench/src/sidebar.c, workbench/src/sidebar.h
The user can now remove a selected file or directory. Closes #711.
The user has to confirm the action and is warned that it cannot be undone.
In case a directory is removed, then first all files will be removed. The workbench plugin only removes that files in a directory which are displayed in the sidebar. That means files that are not displayed because they do not match the file patterns will not be removed. After removing all files, all sub-directories and finally the selected directory will be removed. This will fail if a directory is not really empty.
If removing of a file or directory fails, then a message is output.
=> workbench: remove files or directories.

build/workbench.m4, workbench/src/dialogs.c, workbench/src/plugin_main.c, workbench/src/wb_monitor.c, workbench/src/wb_monitor.h, workbench/src/wb_project.c, workbench/src/workbench.c
This removes the dependency/the requirement for GLib version 2.46.
=> workbench: use simple/old file monitor events only

workbench/src/wb_project.c
Prevent debug messages by checking if the file path is a regular file or not.
=> workbench: fixed tag-manager warning. Fixes #713.

treebrowser/src/treebrowser.c
Geany depends on Gtk version 2.24 so all version checks for a lower version than 2.24 are needless.
=> treebrowser: removed needless Gtk version checks

workbench/src/wb_project.c
This fixes the broken live-update. The feature did not work since commit dcc37957e917a2e8c2f3e5d483c9a832eceff1e0. The reason was that the sub-directories were not added to the file-table and so no file monitor was created for them. The live-update only worked for the main directories but not for their sub-directories.
=> workbench: fix broken live-update

geanyinsertnum/src/insertnum.c
Added ellipsis to make the plugin conform to GNOME's UI paradigm, also see #251.
=> geanyinsertnum: added ellipsis

workbench/src/dialogs.c, workbench/src/plugin_main.c, workbench/src/sidebar.c, workbench/src/workbench.c, workbench/src/workbench.h
The user can now activate the option "Expand on hover". If the option is activated then a tree node in the workbench sidebar will expand or collapse by hovering with the mouse cursor over it.
=> workbench: added option "Expand on hover"

geanyctags/src/geanyctags.c
This should fix problems when the project file (and as a result the tags
file too) contains spaces.
Fixes the geany-plugins part of #738
=> geanyctags: Add apostrophes around generated tags file

build/markdown.m4, markdown/src/Makefile.am, markdown/src/viewer.c, markdown/src/viewer.h
Markdown-specific changes from #677.
=> Markdown: add support for webkit2gtk

vimode/src/cmds/motion.c
SCI_LINEDOWN goes down only one display line, hence when line wrapping
was enabled and a line wrapped over more than two lines, it was
impossible to go to the next actual line when pressing j.
Note that this still doesn't emulate vim behavior correctly where
caret-x position is saved for actual lines and not display lines. But
this change at least makes j go the next line when wrapping is enabled.
Note that I'm not completely sure whether this change retains all workarounds [mentioned in `cmd_goto_up`](https://github.com/geany/geany-plugins/blob/341cab4e13c122b2b74e6f31a43be9adc653f8af/vimode/src/cmds/motion.c#L51-L54).
=> vimode: Fix goto_down with line wrapping

geanyvc/src/geanyvc.c, workbench/src/dialogs.c
=> FIX: Spaces after dots in translatable strings

build/scope.m4, po/POTFILES.in, scope/data/Makefile.am, scope/data/scope_gtk3.glade, scope/src/Makefile.am, scope/src/conterm.c, scope/src/plugme.c, scope/src/prefs.c, scope/src/prefs.h, scope/src/scope.c, scope/src/utils.c, utils/src/Makefile.am, utils/src/gp_gtkcompat.h, utils/src/gp_vtecompat.c, utils/src/gp_vtecompat.h
This PR adds GTK3 support to the scope plugin, but still keeps GTK2 support (in contrast to PR #697).
Some compatibility code (macros) were put in the common utils lib so that other plugins can use it on porting to GTK3. So this PR includes changes on scope AND utils.
@frlan: don't merge this - it's work in progress.
But this is **NOT working** yet. **I need help** with the build system:
How can I make scope do the following:
If build against GTK2 use libvte0.17 or newer, e.g. like this:
```
GP_CHECK_PLUGIN_DEPS([scope], [VTE],
[vte >= 0.17])
```
If build against GTK3 use libvte2.91 or newer, e.g. like this:
```
GP_CHECK_PLUGIN_DEPS([scope], [VTE],
[vte-2.91])
```
Thanks for any help in advance.
=> scope: added GTK3 support (keeping GTK2 support)

scope/src/scope.c
This prevents a debug message like 
> "signal 'project-before-save' is invalid for instance '0xd7da10' of type 'GeanyObject'"
being generated on loading the scope plugin.
=> scope: removed invalid signal 'project-before-save' and callback function

build/scope.m4, build/utils.m4, utils/src/Makefile.am
It is not valid to place `AM_CONDITIONAL`s inside a shell condition, because Automake has to known its value in all cases.  Automake is smart enough to detect it if used in a AutoShell conditional (like `AS_IF`/`AS_CASE`/...), but can't work any magic inside a pure shell conditional (if/case/...). So, move the `AM_CONDITIONAL` outside the conditional, as the value is already conditional anyway.
This PR also cleans up the conditional a little bit by giving it a plugin-specific name, and removing irrelevant test fro the condition (whether or not the plugin is enabled has little to no relevance here, and the plugin won't be built anyway).
=> Scope: fix Automake conditional when building for Windows

scope/src/prefs.c, scope/src/scope.c
=> scope: removed unnecessary includes of 'vte/vte.h'

scope/src/conterm.c, scope/src/memory.c, scope/src/utils.c
Fixed ```sizeof``` without parentheses, spaces instead of tab and a compiler warning.
=> scope: small code cleanup. See #794.

treebrowser/src/treebrowser.c
Using generic xdg-open that will open associated file manager is better than hard-coded nautilus that works only for Gnome/Unity.
=> treebrowser: use xdg-open for external open command

build/gtk.m4
Do not require pkg-config to emit spaces around elements in its `--print-requires` output.
This should fix Geany GTK version check on OpenBSD 6.4.
---
@andy5995 could you check this and see if it helps?  Once configured, you should get something like that (obviously with GTK2 version of it if you've got a GTK2 build):
```shell
$ grep ^GP_GTK_ config.log 
GP_GTK_PACKAGE='gtk+-3.0'
GP_GTK_VERSION='3.0'
GP_GTK_VERSION_MAJOR='3'
```
=> Don't rely on a pkg-config output formatting detail

debugger/src/bptree.c
I noticed this warning on buster and slack current, both using gcc8.
This fixes the warning (caused by mixed tabs/spaces indentation):
```
bptree.c: In function ‘on_hitscount_changed’:
bptree.c:373:5: warning: this ‘if’ clause does not guard...
[-Wmisleading-indentation]
if (oldcount != count)
^~
bptree.c:376:2: note: ...this statement, but the latter is misleadingly
indented as if it were guarded by the ‘if’
gtk_tree_path_free(tree_path);
^~~~~~~~~~~~~~~~~~
```
=> debugger/bptree.c:fix compiler warning

git-changebar/src/gcb-plugin.c
Namely rename the deprecated git_buf_free to git_buf_dispose and change
giterr calls to git_error.
=> git-changebar: fix compatibility with libgit2 0.28 API

geanyctags/src/geanyctags.c
=> geanyctags: use new plugin API

vimode/src/cmd-runner.c, vimode/src/vi.c
By last-minute mistake made before the initial plugin release, none of the
repeat commands worked because numbers were removed from the key press
list. This patch fixes that issue.
This is what happens when the author of the plugin actually doesn't use
what he has created.
=> vimode: Fix repeated commands like 10dd not working

geanyvc/src/geanyvc.c
Remember the last 10 commit messages and offer a dropdown in the commit
dialog to choose one of the last commit messages.
One of my use cases is that there was an error on executing `git commit` and so the commit and its message is lost(in this case any feedback of the failed process is missing in the UI but that's another story). With the history, I can restore the message easily.
Another use case is that one might want to repeat the same commit message for multiple commits (i.e. same change in various repositories or whatever).
=> GeanyVC: Add a commit message history

scope/src/local.c
The context menu item "Modify" is now only set to sensitive=TRUE if a local variable is selected. This prevents a crash that happened if "Modify" was selected without having a local variable selected. Fixes #825.
=> scope: fixed "Modify" menu item being active without selection

scope/src/debug.c
If the user tries to start debugging and no executable is set an error message appears: _'No executable set. Please set an executable under "Debug/Setup Program".'_
=> scope: show error message if no executable is set

scope/data/scope_gtk3.glade
The height of the text view was fixed by setting a height size request for the surrounding GtkVBox. Fixes #829.
=> scope: corrected height of "Environment" GtkTextView

geanyextrasel/src/extrasel.c
The workaround seems unneeded now, and even causes problems.
Reverses PR #568 from Apr 2017.
=> Undo workaround for rectange selection cancel bug

addons/src/addons.c
Switched to new plugin API:
- moved all plugin API code to the end of file
- therefore also some function declarations became needless and could be removed
- added help function
=> addons: use new plugin API

defineformat/src/defineformat.c
=> defineformat: use new plugin API

automark/src/automark.c
=> automark: use new plugin API

build/debugger.m4, debugger/src/Makefile.am, debugger/src/btnpanel.c, debugger/src/cell_renderers/cellrendererbreakicon.c, debugger/src/cell_renderers/cellrendererbreakicon.h, debugger/src/cell_renderers/cellrendererframeicon.c, debugger/src/cell_renderers/cellrendererframeicon.h, debugger/src/cell_renderers/cellrenderertoggle.c, debugger/src/cell_renderers/cellrenderertoggle.h, debugger/src/dconfig.c, debugger/src/debug.c, debugger/src/dpaned.c, debugger/src/gui.c, debugger/src/plugin.c, debugger/src/stree.c, debugger/src/tpage.c
This pull request is heavily based on #645 from which it borrows the majority of the changes.
The main improvement is that this one doesn't break compatibility with GTK2 (there are macros which select the correct code path accordingly).
I also removed some cosmetic-only changes to maintain the differences as small as possible and provided a corrected code for console font selection (which was just commented out in the original pull request).
This was successfully tested on Centos 7.5 with stock development packages.
=> 'Debugger' plugin port to GTK3 with GTK2 compatibility

MAINTAINERS
The plugin is not orphaned. I created it and still maintain it.
@frlan: sorry, I missed your commit that added it to the MAINTAINERS file.
=> workbench: plugin status is 'maintained'

vimode/src/excmd-prompt.c
Vi seems to use a separate history for commands (starting with ':')
and searches (starting with '/' or '?'). Let's do the same.
=> vimode: Separate command and search history

scope/README
This fixes an ugly error message on the geany-plugins website, see https://plugins.geany.org/scope.html.
=> scope: fixed missing escape character in README

projectorganizer/README
This fixes an ugly error message on the geany-plugins website, see https://plugins.geany.org/projectorganizer.html.
=> projectorganizer: fixed too short title underline in README

lipsum/src/lipsum.c
This fixes a deprecation warning in the lipsum plugin for gtk3. No functional changes.
=> lipsum: fixed deprecated gtk call for gtk3

tableconvert/src/tableconvert_ui.c
This fixes a deprecation warning in the tableconvert plugin for gtk3. No functional changes.
=> tableconvert: fixed deprecated gtk call for gtk3

utils/src/gp_gtkcompat.h, workbench/src/dialogs.c, workbench/src/popup_menu.c, workbench/src/sidebar.c
This fixes some deprecation warnings in the workbench plugin for gtk3. No functional changes.
=> workbench: fixed deprecated gtk calls for gtk3

geanyextrasel/src/extrasel.c
I am a bit uncertain about the version check but if I understood correctly, GDK is part of GTK.
=> extrasel: fixed deprecated gtk call

geanyvc/src/geanyvc.c
Initialize two pointers (although not required) to silence two errors reported on ```make check```:
```
geanyvc.c:1374: error: Uninitialized variable: list_item
geanyvc.c:2200: error: Uninitialized variable: ptr
```
=> geanyvc: silence check errors

autoclose/src/autoclose.c
This fixes a deprecation warning in the autoclose plugin for gtk3. No functional changes.
A little side note:
I first thought I could use ```gtk_container_add()``` on gtk 2 and 3 because of this deprecation notice in the gtk documentation:
> gtk_scrolled_window_add_with_viewport has been deprecated since version 3.8 and should not be used in newly-written code.
> gtk_container_add() will automatically add a GtkViewport if the child doesn’t implement GtkScrollable.
But the function only works that way under gtk3. A test with gtk2 revealed that the function does not work that way with the result that in this case the scroll bar was missing in the autoclose configuration dialog.
=> autoclose: fixed deprecated gtk call for gtk3

automark/src/automark.c
=> automark: move initialization behind DOC_VALID check. Fixes #574.

build/geanynumberedbookmarks.m4, geanynumberedbookmarks/src/Makefile.am, geanynumberedbookmarks/src/geanynumberedbookmarks.c, utils/src/gp_gtkcompat.h
This fixes some deprecation warnings in the geanynumberedbookmarks plugin for gtk3. No functional changes.
=> geanynumberedbookmarks: fixed deprecated gtk calls for gtk3

workbench/README, workbench/src/menu.c, workbench/src/plugin_main.c
After confirming changed settings with _"OK"_ they will now immediately be written back to the workbench file. Therefore the menu item _"Workbench / Save"_ became useless and has been removed. Closes #841.
=> workbench: save settings immediately

workbench/README, workbench/src/sidebar.c
Give the sidebar a name/CSS ID to enable dedicated styling. Also added a section with an example to the README.
=> workbench: give sidebar a name to enable dedicated CSS styling

workbench/README, workbench/src/dialogs.c, workbench/src/plugin_main.c, workbench/src/sidebar.c, workbench/src/workbench.c, workbench/src/workbench.h
This PR adds a simple config option to disable or enable tree lines in the workbench's sidebar tree.
(This also adds the missing description for the option _"Expand on hover"_ to the README file)
=> workbench: added option to enable or disable tree lines

workbench/src/Makefile.am, workbench/src/idle_queue.c, workbench/src/idle_queue.h, workbench/src/plugin_main.c, workbench/src/tm_control.c, workbench/src/tm_control.h, workbench/src/wb_project.c, workbench/src/wb_project.h
This commit moves all access to TMSourceFiles/the tagmanager API into a dedicated file ```tm_control.c```. Calls from the workbench plugin to the tag-manager API may now only appear in this file. Also all calls are synced using a idle-queue managed in ```idle_queue.c``` (using ```plugin_idle_add()```). This way the file lists in the workbench projects is completely de-coupled of any TMSourceFile related data/references. Fixes #866.
(Calls to the tag-manager API were synced before also. But the implementation was not very clean and therefore contained errors/code where the tag-manager API was called directly - which could lead to crashes)
=> workbench: revised tag-manager control/usage

workbench/README, workbench/src/plugin_main.c, workbench/src/popup_menu.c
This removes the item _"Save project"_ from the popup menu and automatically saves a project if something is changed (e.g. directory added/removed).
This also fixes some situations in which saving of the workbench file was missing (e.g. a change in the workbench bookmarks). See #841.
=> workbench: auto-save project on change

lineoperations/src/lineoperations.c
Oops, I think I broke Travis CI. 
I am returning a (small) structure when I should be using pointers.
This commit should fix this mess, my apologies.
=> lineoperations: fixed -Werror=aggregate-return

build/treebrowser.m4, treebrowser/src/Makefile.am, treebrowser/src/treebrowser.c
Apart from fixing a load of deprecation warnings on gtk3 this also fixes two gtk3 related problems in the treebrowser plugin:
- lines in the Treeview had a red color - now they are black like under gtk2
- the text field turned red if the path entered wasn't a valid directory - this did not work under gtk3 before but now it works
The gtk2 behavior is unchanged and there are also no functional changes.
If this get's merged PR #279 would become needless and could be closed un-merged.
=> treebrowser: fixed deprecated gtk calls for gtk3

updatechecker/src/updatechecker.c
The old URL is kept running only to support old versions.
=> UpdateChecker: Use new service URL

scope/src/Makefile.am, scope/src/tests/unittests.c, scope/src/tests/utils_test.c, scope/src/tooltip.c, scope/src/utils.c, scope/src/utils.h
Scope automatically evaluates an expression if the mouse pointer is hovered over it. But before this change it only evaluated words. E.g. if the mouse was hovered over ```structa->item1``` then scope would have evaluated ```structa``` or ```itemb``` depending on the exact position of the mouse pointer. With this change it will instead evaluate the value of ```structa->item1```.
=> scope: Improved evaluation on-hover

po/POTFILES.in, workbench/README, workbench/src/Makefile.am, workbench/src/menu.c, workbench/src/plugin_main.c, workbench/src/search_projects.c, workbench/src/search_projects.h, workbench/src/sidebar.c, workbench/src/workbench.c
The feature lets the user search for projects to add them to the Workbench. After selecting the menu item, the user can select a directory to search through. The directory and it's sub-directories are scanned for project files (```*.geany```). All found files are listed and after scanning is done the user can select the projects which shall be added to the Workbench.
The dialog is not modal - the user can do other work during the scanning of the directory.
=> workbench: added new feature "Search projects"

scope/src/break.c, scope/src/inspect.c, scope/src/local.c, scope/src/memory.c, scope/src/menu.c, scope/src/register.c, scope/src/stack.c, scope/src/store/scptreestore.c, scope/src/thread.c
This fixes the crash described in #824 (and two more potential crashes).
=> scope: prevent usage of invalid iters (GtkTreeeIter)

devhelp/devhelp/Makefile.am
This was [changed upstream](https://github.com/GNOME/devhelp/commit/94f3661dbc3d0a228a78ff4a4d38b076b7a221b8) some unknown time ago.
I didn't really test this properly, hoping Travis CI will do it for me :)
See comments in #864
=> Devhelp: Fix embedded library's use of glib-genmarshal

scope/src/utils.c
This fixes the broken windows build. The issue was introduced by PR #823.
=> scope: fixed misplaced '#define SCOPE_MAX_EVALUATE_EXPR_LENGTH'

addons/src/ao_colortip.c
Added code needed to show hexadecimal numbers as colors. This is useful for any computer languages and/or syntax that represents numbers in the format `0x123456` (such as the colorscheme themes in Geany).
=> Added additional color format to ao_colortip.c in "Addons"

build/workbench.m4, utils/src/filelist.c, utils/src/filelist.h, workbench/README, workbench/src/Makefile.am, workbench/src/dialogs.c, workbench/src/dialogs.h, workbench/src/plugin_main.c, workbench/src/popup_menu.c, workbench/src/utils.c, workbench/src/utils.h, workbench/src/wb_project.c, workbench/src/wb_project.h
In the directory settings it is now possible to choose between a workbench or a git file filter. The later is new and lets git decide which files to display depending on the contents of the ```.gitignore``` file.
This also adds a new function to the utils-lib called ```gp_filelist_scan_directory_callback()```.
See this example screenshot:
=> workbench: added option to let git decide which files to display

addons/src/ao_colortip.c
Changed the hard-coded color-tip string to be set via macros which can be used to set the size of the color-tip at compile-time. This is helpful for making the color-tip larger on 4K screens or for people with less acute vision.
=> Added macros to ao_colortip.c in "Addons"

geanyprj/src/project.c
This is a very small code cleaning of geanyprj plugin.
It actually contains only one commit to use C designated initialisers for arrays initialisation when their cells indexed matches an enum.
=> geanyprj: small code cleaning

lineoperations/src/lineoperations.c
Added keybindings for all menu items of the Line Operations plugin.
=> lineoperations: added keybindings. See #832.

addons/src/ao_doclist.c
Fixed document list menu position bug when the tool button has been moved to the toolbar overflow menu
- tested on builds of Geany 1.35 for Gtk versions 3.22.30 and 2.24.32
=> Fixed document list menu position bug

updatechecker/src/updatechecker.c
I think that this might be a small memory leak:
The string `config_file` is allocated in `init_configuration()` when the plugin is loaded, and then again in the callback function `on_configure_response()`.
From what I can tell it's not being freed every time the callback is called.
=> updatechecker: remove duplicate config_file string allocation

lineoperations/ChangeLog, lineoperations/README, lineoperations/src/Makefile.am, lineoperations/src/linefunctions.c, lineoperations/src/lineoperations.c, lineoperations/src/lo_fns.c, lineoperations/src/lo_fns.h, lineoperations/src/lo_prefs.c, lineoperations/src/lo_prefs.h, po/POTFILES.in
This PR is in response to #819.
Changes:
- add preferences option: 'Use collation based string compare'
- `getcmpfns()` returns either `g_utf8_collate` or `strcmp` function pointer to line operations function based on user preference
Minor:
- add help function to redirect to online documentation
- split files into `lo_prefs` and `lo_fns`
- sorry about all the annoying indentation / spacing changes / file renaming.
I'm open to hear any suggestions/improvements.
=> lineoperations: add support for locale-aware sorting 

NEWS
This issue was only a temporary problem during 1.36 development. The issue that was fixed did not exist in 1.35 so this bugfix shouldn't be mentioned in NEWS.
=> NEWS: removed 'Fix misplaced '#define SCOPE_MAX_EVALUATE_EXPR_LENGTH (PR #885)'

projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-sidebar.h
=> projectorganizer: Add a keybinding for for focusing the sidebar

overview/overview/overviewscintilla.c
While this might not be necessary technically, cppcheck complained:
overviewscintilla.c:800:53: note: Calling function 'overview_scintilla_get_overlay_color', 2nd argument '&color' value is <Uninit>
overview_scintilla_get_overlay_color (self, &color);
^
overviewscintilla.c:1146:11: note: Uninitialized variable: color
=> Overview: initialize color variables

projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-utils.c, projectorganizer/src/prjorg-utils.h
There is more choice when using icons based on freedesktop icon name
so we can use better icons.
This is mainly because of "New file" and "New directory" icons in the popup menu in the sidebar which should use action icons instead of icons of a file and a directory (with some themes all action icons are black and white while document/directory icons have a color which looks inappropriate in this case).
=> projectorganizer: don't use stock icons

pairtaghighlighter/src/pair_tag_highlighter.c
I think these are useful to working with xml pair tags.
- Editor Menu option for jumping to matching tag
- Selecting to matching tag
Related to: https://github.com/geany/geany-plugins/pull/763
=> Utilities for Pair Tag Highlighter

build/compat.m4, build/cppcheck.m4, build/cppcheck.mk
This fixes build with recent versions of *cppcheck* with some plugins using `PLUGIN_VERSION_CHECK()` macro, like the *latex* plugin.
---
@eht16 already tested this with the nightly build environment, but I'm PRing this to make sure the CI tests here also pass.  And extra review is always welcome ;)
=> cppcheck: Set Geany include path for it to find header files

projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-project.h
When file operations were added to project organizer, the plugin started
showing empty directories in the sidebar because they are useful e.g.
for creating new files inside them. This may be unwanted e.g. in projects
with many directories which are irrelevant to the code.
This patch makes this configurable on a per-project basis.
Fixes #881
=> projectorganizer: Make showing empty directories in the sidebar configurable

geanyvc/src/Makefile.am
=> GeanyVC: Use geanyvc_la_LIBADD to add libs needed for unittests

markdown/src/markdown-gtk-compat.c
To convert from range 0.0-1.0 to 0-255, the values must be divided by 255.0 and not 256.0. The same in the opposite direction.
=> Markdown: fix colors in gtk3

vimode/src/cmd-runner.c, vimode/src/excmd-prompt.c
Use gtk_accelerator_get_default_mod_mask() which should ignore caps lock
and num lock keys for us.
Fixes #941.
=> vimode: Correctly ignore unwanted modifiers

MAINTAINERS
Accepting maintainership of the GeanyVC plugin per @frlan invitation.
It would be nice to have GitHub notify @nomadbyte anytime an issue/PR is labeled with [plugin/geanyvc](../../labels/plugin/geanyvc) tag.
=> GeanyVC: Accept maintainership

debugger/src/tpage.c
This fixes a cppcheck 2.2+ confusion about uninitialized widgets array
and also makes the code a bit more readable.
Closes #1014.
=> Debugger: Fix cppcheck false positive warning

autoclose/README, automark/README, codenav/README, defineformat/README, geanypg/README, lipsum/README, pretty-printer/README, shiftcolumn/README, spellcheck/README, updatechecker/README
Follow-up of #981 to fix restructuredText formatting and add the install instruction link to other plugins' READMEs as well which are similarly structured.
Closes https://github.com/geany/geany/issues/2508.
=> #981: ReadMe install instructions

build/geany-plugins.nsi
Loosen the G-P Windows installer version check for Geany to require only a matching major and minor version, i.e. we now ignore the patch level.
So for example, Geany-Plugins 1.37 can be installed for Geany 1.37.1 without warnings.
As discussed in geany/geany/issues/2655.
=> Windows installer: ignore patch level version when checking for Geany

treebrowser/src/treebrowser.c
Fixes #675 
`on_treeview_changed` is triggered during `treebrowser_tree_store_iter_clear_nodes`, leading to a double-delete.
Consistent (as far as I can tell) reproduction steps:
1. Create a folder
2. Create two new files in folder
3. Delete second file
=> TreeBrowser: Avoid double node clear

pretty-printer/src/PrettyPrinter.h
Hi,
I'm maintaining the `geany-plugins` package for Arch Linux.
When compiling the latest version of geany-plugins, I get this error:
```
PrettyPrinter.h:55:22: error: two or more data types in declaration specifiers
55 | typedef unsigned int bool;
|                      ^~~~
```
Including `<stdbool.h>` and removing the typdef for `bool` solves this issue.
Tested on GCC 10.2.0.
Thanks for creating and maintaining Geany and Geany Plugins! They are both pretty sweet and usually unproblematic to package.
Fixes #1023
=> Use stdbool.h istead of redefining bool

geanylua/glspi_sci.c, geanymacro/src/geanymacro.c, geanynumberedbookmarks/src/geanynumberedbookmarks.c, git-changebar/src/gcb-plugin.c
Fixed a crash of geany by the git-changebar plugin by changing a glong type to sptr_t in the SCI_ADDTEXT invoking (MinGW64 build)
=> Fixed a crash of geany by the git-changebar on SCI_ADDTEXT

geanyprj/README, latex/doc/latex.html
See also #1049.
There are two occurrences left:
`scope/docs/scope.html:<p>A. Your Geany does not support this signal. Either apply the patch from Geany sourceforge patch tracker <a href="http://sourceforge.net/tracker/?func=detail&amp;aid=3594050&amp;...`
The referenced issue exists (https://sourceforge.net/p/geany/patches/21/) but will also be deleted some time when we clean the Geany Sourceforge project as well.
I tend to keep the reference as is, put up with having a broken link. Other ideas are welcome.
`treebrowser/ChangeLog:  (FIXED) http://sourceforge.net/tracker/?func=detail&aid=3034450&group_id=222729&atid=1056532`
I would keep this as is, manipulating a ChangeLog entry feels as wrong as having a broken link there.
=> Replace Sourceforge references

vimode/README, vimode/src/Makefile.am, vimode/src/cmd-params.c, vimode/src/cmds/excmds.c, vimode/src/cmds/excmds.h, vimode/src/excmd-params.h, vimode/src/excmd-runner.c
These patches add the following ex commands:
```
:y[ank]
:pu[t]
:u[ndo]
:red[o]
:<
:>
:d[elete]
:j[oin]
:co[py]
:m[ove]
```
Fixes the `:delete` command missing part of #1060.
=> vimode: add some more ex commands

vimode/src/cmd-runner.c
For
abcde;
simple 't;' does the right thing and places the cursor on top of character
'e' just before ';'. However, for composed commands such as 'dt;', vim
also deletes the character 'e' which vimode currently doesn't.
Vim behaves in a bit inconsistent way regarding this behavior - while
for 'dw' (delete all until next word) it doesn't delete the first character
of the next word onto which the cursor is placed, for 'de' (delete until
next word end) it includes the final character of the deleted word. This
behavior makes sense from the use case point of view but makes handling
of such situations inconsistent.
This patch lists functions which behave this way and includes the
destination character to the selection.
Fixes #1052.
=> vimode: Add special handling to include destination char for some commands

vimode/src/cmd-runner.c, vimode/src/context.h, vimode/src/vi.c
Currently, '.' only repeats the last command inserted in the command mode
and doesn't repeat text inserted in the (just exited) insert mode which
vim does.
Since we already support commands like
10iwrite_text_to_be_repeated_10_times<esc>
we can reuse the code also for the '.' command.
Fixes #1011
=> vimode: Enable '.' to also repeat last inserted text

vimode/src/cmd-runner.c
This special command handling is not related to insert mode and causes
problems in "insert mode for dummies".
Fixes #1075.
=> vimode: Ignore special command handling in insert mode

vimode/src/keypress.c
No vi command uses the command key so we can ignore such key presses
so Geany's keybindings can be performed instead.
Fixes #991
=> vimode: ignore key-presses containing command on macOS

po/pt.po
Corrected the string where it refers to a number and not the word "no".
#. Translators: Number is meant at this point.
#: ../addons/src/ao_bookmarklist.c:342
msgid "No."
msgstr "Nº."
I also corrected some strings where they started with lower case letters
=> Update portuguese(pt) translation

.travis.yml
While we don't support GTK2 anymore, the Travis CI config still tried to build it but actually built against GTK3 twice because Geany is always built against GTK3.
I'm going to migrate this soon to Github Actions and so this is only a quick'n'dirty attempt to prevent unnecessary builds.
=> Remove GTK2 jobs from Travis CI

addons/src/ao_openuri.c, addons/src/ao_tasks.c, geanydoc/src/config.c, geanydoc/src/geanydoc.c, geanymacro/src/geanymacro.c, geanyprj/src/sidebar.c, geanyprj/src/utils.c, geanyvc/src/geanyvc.c, geanyvc/src/utils.c, geanyvc/src/vc_svn.c, spellcheck/src/gui.c, spellcheck/src/scplugin.c, treebrowser/src/treebrowser.c
`setptr` is deprecated and a candidate for removal.  This PR replaces instances with `SETPTR`.
Affected plugins: addons, geanydoc, geanymacro, geanyprj, geanyvc, spellcheck, treebrowser
See geany/geany#3019.
=> Replace deprecated setptr macro with SETPTR

treebrowser/src/treebrowser.c
Uses the URI to get parent instead of the tree to allow for insertion at the top level.
Fixes #1152
=> TreeBrowser: Allow new file/folder in top level

projectorganizer/src/prjorg-utils.c
Use system trash when removing files/folders in Project Organizer.
=> Project Organizer: Use system trash for file/folder removal

spellcheck/src/gui.c, spellcheck/src/scplugin.c
=> SpellCheck: Sync toggle via keybinding and button

debugger/src/bptree.c, debugger/src/breakpoints.c, debugger/src/callbacks.c, debugger/src/cell_renderers/cellrendererframeicon.c, debugger/src/cell_renderers/cellrenderertoggle.c, debugger/src/dbm_gdb.c, debugger/src/dconfig.c, debugger/src/debug.c, debugger/src/debug_module.h, debugger/src/envtree.c, debugger/src/gdb_mi.c, debugger/src/markers.c, debugger/src/plugin.c, debugger/src/vtree.c, debugger/src/watch_model.c, debugger/src/wtree.c
This is an excellent and quite complex plugin. Fixing typos in the code comments helps new devs to get familiar with the plugin's design and logic. Well, it helped me at least...
=> Debugger: Fix typos in code comments

addons/src/ao_bookmarklist.c
For some filetypes (more specifically some Scintilla lexers) it might
happen that an event with modificationType SC_MOD_CHANGEMARKER is
sent and so the current line is added as bookmark again.
To avoid this, check if the current line has already a bookmark and
update it in this case.
Might be related to #964.
=> Addons: Bookmarks: Prevent duplicating bookmarks when editing line

geanyvc/src/vc_git.c
=> GeanyVC:(Git) Fallback to `git rev-parse` for getting the repo/worktree's top directory

scope/src/stack.c
Fixes warnings with clang 15+
scope/src/stack.c:168:11: error: incompatible pointer to integer conversion initializing 'gboolean' (aka 'int') with an expression of type 'void *' [-Wint-conversion]
gboolean entry = NULL;
^       ~~~~
1 error generated.
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> scope: Use 0 instead of NULL for gboolean

geanygendoc/src/ggd-tag-utils.c, geanygendoc/src/ggd.c
tm_tag_file_t has never been used by Geany so the check is unnecessary.
In the latest version of Geany this tag was renamed to tm_tag_local_var_t
and used for local variables which breaks compilation.
Those things that appear as big diffs on github are just unindents after the removed `if` check.
=> geanygendoc: Remove all sanity checks testing if tag is tm_tag_file_t

git-changebar/src/gcb-plugin.c
This should fix #1164 , and replaces #1165.
BEWARE: I did NOT test this with libgit2 1.4, that I don't have yet. I might go to the trouble of building it and all, but for now this is a theoretical PR, but if libgit2 1.4 users can verify it it'd be great.
=> git-changebar: Add support for libgit2 1.4

MAINTAINERS
I no longer use Geany, so I cannot maintain the treebrowser plugin.  Best of luck to anyone who wishes to continue its development.
=> Remove self as maintainer for treebrowser plugin

Makefile.am, build/cppcheck-geany-plugins.cfg, build/cppcheck.mk, codenav/src/goto_file.c, debugger/src/dbm_gdb.c, debugger/src/debug.c, geanyvc/src/utils.c, geniuspaste/src/geniuspaste.c, latex/src/latex.c, treebrowser/src/treebrowser.c, workbench/src/sidebar.c, workbench/src/wb_project.c
Recent versions of cppcheck (2.9+) seem to require this configuration. The gtk.cfg configuration file is part of cppcheck itself.
Closes #1196.
=> Add --library=gtk to cppcheck

build/bundled/gpgme.m4
`gpgme.m4` was bundled in geany-plugins 12 years ago in https://github.com/geany/geany-plugins/commit/2535603ae1a211d68d5f2f1122fb5e8972e0b754, and now it's sufficiently outdated that it's causing trouble for the migration from `gpgme-config` to `gpgrt-config`.
This PR updates it to the current version from [gpgme git master](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=src/gpgme.m4;hb=2ba11f9bfb1f51a481eb1240b8cf2c8ad260c222)
Fixes: #1213
=> Update bundled gpgme.m4

addons/src/addons.c, addons/src/addons.h, addons/src/ao_wrapwords.c
Instead of hardcoding the count of previously defined keybindings in the Addons plugin, use the already available enum counter.
While testing #1182, I noticed that there is a mismatch between the pressed keybinding with the configured replacement. The Wordwrap plugin had the keybinding count of all keybindings of the Addons plugin hardcoded and of course it changed since then but the hardcoded magic number was not updated.
Instead of hardcoding, use the enum counter constant.
=> Addons: Fix Wordwrap wrong keybinding use

geanylua/glspi_kfile.c, geanylua/glspi_run.c, geanylua/gsdlg_lua.c
With GCC 11.3:
warning: implicit declaration of function ‘luaL_openlib’; did you mean ‘luaI_openlib’? [-Wimplicit-function-declaration]
Lua 5.1 replaced luaL_openlib with luaL_register
https://www.lua.org/manual/5.1/manual.html#7.3
=> GeanyLua: Use luaL_register instead of luaL_openlib

build/webhelper.m4, webhelper/src/Makefile.am, webhelper/src/gwh-browser.c, webhelper/src/gwh-browser.h, webhelper/src/gwh-plugin.c, webhelper/src/gwh-settings.c
Based off work from @hyperair that was merged at some point in #677, but reverted since then (see there). This adds a couple bits on top to fix some issues, and I believe the "meh no GTK2" whining of mine is lost to time and the fact there's no supported webkit for GTK2 anymore anyway.
BEWARE: this has been given little testing in the 2020s, I just rebased, merged a couple branches to the point there diffed empty, and did some very basic testing (it builds, it runs, and *seems* to work).  Take it, leave it, improve it, comment on it, etc.  I'll be there try not to forget looking at this for any comment though :wink: 
NOTE: it's not at 100% feature-parity with the old version, mostly because of API changes regarding the inspector (II[RU]C, docking settings are not as controllable anymore), …
=> webhelper: Port to webkit2gtk

debugger/src/debug.c, debugger/src/stree.c
- By the original design, the debugger allows thread context switching only
interactively, while in the Call Stack pane (in Stopped mode). This is
being handled directly through GtkTreeView::cursor-changed event.
- However, this event was also getting triggered when clearing the latest
thread's Call Stack after continuing the execution (Running mode).
- This behavior does not seem to have being intended, and it lead to a
number of issues: stepping hangs, corruption of GDB output processing,
unnecessary attempts at opening of source files corresponding to thread's
call-stack frames.
- To avoid all of these issues, GtkTreeView::cursor-changed event is left
unhandled while clearing the frames. Also the handler for thread-context
switching is allowed processing only in debugger's Stopped mode …
=> Debugger: Fix debugging of multi-threaded programs

vimode/src/excmd-prompt.c
On macOS there seems to be some bigger default height so the excmd popup
is too tall. When default-height is set to 1, it is automatically resized
to the height of the text entry it contains and has correct size on both
linux and macOS.
=> vimode: Set default height of excmd popup to a small number

vimode/src/keypress.c
It seems that GDK_MOD2_MASK isn't the right modifier to check for
command pressed - its mapping is platform-specific and while this works
on macOS, it has undesirable side-effects on linux. Use GDK_META_MASK
instead which based on my testing seems to do the right thing both on
macOS and linux.
Fixes (1) in #1136
=> vimode: fix escape not working when numlock is on

vimode/src/cmds/edit.c
This pull request fixes the problem related to caret position change reported in #1136.
=> vimode: Fix caret position change when performing line operations

projectorganizer/src/prjorg-main.c, projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-project.h, projectorganizer/src/prjorg-utils.c, projectorganizer/src/prjorg-utils.h
Resolves #1121.  Resolves geany/geany#2946.
If file is a header and a corresponding source file is found in the same directory, set the header filetype to match the source filetype.  Otherwise, search the project for the corresponding source file.  This is useful for `.h` files, which are ambiguous for C/C++.  Does not address the filetypes of isolated header files.
=> Project Organizer: Set header filetype to match source filetype

projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-project.h, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-sidebar.h
File manager/terminal are opened at the location of the selected file in the tree view.  If nothing is selected, the location of the current document is used.  If the current document does not have a path, the project directory is used.  If the project directory cannot be located, the user's home directory is used.
The file manager is opened with the path as the first argument.
The terminal path is set using the PWD.
Note: Does not accept any %f %u %d %p %etc specifiers.  This is left for a future PR if needed.
=> Project Organizer: Add option to open current folder in file manager and terminal

projectorganizer/src/prjorg-main.c, projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-project.h, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-sidebar.h
This pull request consists of 2 patches:
1. It remembers selection in the sidebar and on project reload the selected row is restored.
2. It stores/loads expanded paths to/from the project file so the state of the tree gets restored when switching between projects.
=> projectorganizer: Restore tree state in the sidebar

.github/workflows/build.yml, build/ci_mingw64_geany_plugins.sh, build/gtk-bundle-from-msys2.sh
Please welcome a new way to build Geany and Geany-Plugins for Windows in the CI.
What's in here:
- the workflow job to checkout Geany-Plugins, Geany and Infrastructure repositories
- use the supporting scripts in https://github.com/geany/infrastructure/tree/add_ci_builders/builders to
- build a Docker image with a full MSYS2 installation (or pull the image from the Geany Docker registry if available)
- use this Docker image to:
- build Geany and create a release-like installer for it as build dependency for the G-P build (or use cache if available)
- install Geany from the previously built Geany installer
- build Geany-Plugins and create and test an installer
- store the Geany and Geany-Plugins installer as artifact on Github
Mostly all of the work is done in the builder scripts on …
=> Add mingw-w64 (Windows) CI build

vimode/src/Makefile.am
With the latest version of msys, the viw binary fails to link (most probably it should be built as a C++ binary instead of the current plain C binary).
Since this binary is used just for testing purposes, there's no need to build it on Windows so this patch skips the build there to avoid this problem.
Fixes #1255 (hopefully)
=> vimode: Don't build the viw binary on Windows

geanylua/docs/geanylua-ref.html, geanylua/glspi_app.c
* Make platform agnostic.  Resolves [#1230](https://github.com/geany/geany-plugins/issues/1230).
* Fix [infinite loop](https://github.com/geany/geany-plugins/issues/1230#issuecomment-1455210392).
* Update documentation.
Original function wasn't working on X11.  Rewritten function behaves as described in the original documentation, with the exception of allowing only a single instance of `geany.keygrab` to run at a time.  Subsequent instances return `nil` instead of a key name.  This restriction prevents Geany/GeanyLua from losing keyboard access and hanging.
=> GeanyLua: Fix geany.keygrab and remove X11 dependency

projectorganizer/README, projectorganizer/src/prjorg-project.c
Most people use SSDs these days so this shouldn't be a problem.
=> projectorganizer: Increase the file number for automatic indexing to 1000

scope/src/Makefile.am
Without this, cppcheck will throw errors like
```
store/scptreestore.c:1990:37: warning: syntax error [syntaxError]
g_param_spec_boolean("sublevels", P_("Sublevels"),
```
This is probably caused by the P_() macro if GETTEXT_PACKAGE is not set.
Admittedly, this is the easy way to fix or better workaround it. But I guess this is OK. Otherwise, make a better PR :).
The new cppcheck error breaks the night builds on Debian Unstable (https://www.geany.org/download/nightly-builds/).
=> Scope: Define GETTEXT_PACKAGE macro for recent cppcheck versions

addons/src/addons.c, addons/src/ao_tasks.c
Closes #1254.
This is not completely perfect but will do the trick to delay the parsing of tasks in the current document until the main loop has triggered the also delayed colourising of the current document which is necessary for parsing the tasks.
=> Addons: Delay updating of tasks list until document has been colorised

geanypg/src/helper_functions.c
See Scintilla release notes here
https://www.scintilla.org/ScintillaHistory.html
and https://github.com/geany/geany/issues/3095
=> geanypg: Update to Scintilla 5.1.5 SCI_GETSELTEXT change

NEWS, build/geany-plugins.nsi, configure.ac
G-P pendant to https://github.com/geany/geany/pull/3569.
=> Pre-release version bump

build/ci_mingw64_geany_plugins.sh
The previous logic failed on 2.0 to make the new version number 1.99.99. This is fixed now even though the code is not perfect or good at all but should work well enough for its purposes.
See also https://github.com/geany/geany/pull/3594.
The additional log information are in pair with Geany (https://github.com/geany/geany/pull/3568/commits/b18c76edc9eb10a5c0097d4231c387885e2f266f).
=> Fix ci version parser

git-changebar/src/gcb-plugin.c
If the "Change history" feature is enabled in Geany, it might lead to styling issues in the tooltip displaying the diff of the current hunk. So always disable this feature for the tooltip where it is not needed.
I don't think we ever need the "Change history" in the diff tooltip, as the tooltip itself is already the improved version of the change history :).
This happens when the "Change history" feature is enabled in Geany, so it gets also enabled in the Scintilla widget for the tooltip where we don't need it.
For some reason, by setting the margin widths to 0 in https://github.com/geany/geany-plugins/blob/master/git-changebar/src/gcb-plugin.c#L840 the background colors in the Scintilla widget are reset to white (or something else happens with a similar result, I don't understand …
=> GitChangebar: disable Scintilla's Change History in diff tooltip

git-changebar/src/gcb-plugin.c
After updating to Scintilla 5.3.7 the Scintilla popup with the diff against git shows the wrong number.
It seems that gtk_widget_set_size_request() scrolls Scintilla view so despite it was set previously, it isn't set correctly after this call and has to be re-set.
Note that the call to SCI_SETFIRSTVISIBLELINE has to stay at the original location too, otherwise subsequent calculation using SCI_POINTXFROMPOSITION doesn't work because the line may not be visible.
@b4n Does this look OK to you? Maybe there's a better way to fix this problem so take this only as a hint where the problem is.
Fixes #1279
=> git-changebar: Re-set first visible line after Scintilla size request

updatechecker/src/updatechecker.c
The condition is wrong and for version 2.0 it will constantly report there's an update available when upgrading from 1.x (where x > 0).
I had a "visionary" moment regarding possible 2.0 problems and had a look at the updatechecker plugin if it handles major versions - id does, but wrongly (in addition, there are two identical conditions for the "minor" version but the "mini" version check is missing).
I haven't tested this at all (not sure how to test when there's no actual release).
@b4n @eht16 I think this or some other variant of this patch should go to 2.0.
=> updatechecker: Fix logic comparing version numbers

NEWS
Add NEWS for 2.0.
Remarks for the NEWS items:
- I skipped many smaller or non user visible changes or follow-up PRs to not bloat the list too much
- if anyone miss his favorite PR or so, shout out
=> Release 2.0 documentation

projectorganizer/src/prjorg-project.c
Crude but working solution to #1289. 
Disclaimer: I'm not really a C person, so any suggestion on how to improve the code quality are most welcome.
=> avoid parsing opened files when loading project #1289

build/cppcheck-geany-plugins.cfg, build/cppcheck.mk
=> Add missing sign for cppcheck --template argument

geanygendoc/data/filetypes/c.conf, geanygendoc/docs/manual.rst, geanygendoc/src/ggd-tag-utils.c, geanygendoc/src/ggd.c
This is a two-parts fix required for usage with 2.0:
8cad88d72c343fd1091b6dab85ecb226c062a9da: Fix a crash when encountering an unknown tag type (e.g. locals)
3af0bf5117a1143b20286f5ee9fb0a2c35916d6b: Add support for locals, and do something useful with them by default.
Without the first one, triggering documentation generation when a local is the "current" symbol crashes the plugin (and thus Geany).
Without the second one in addition, it's annoying because locals "catch" the generation request, although in most cases they should be skipped.
Both of these are particularly important with 2.0 because we now generate locals for purpose of improved scope completion, and thus we have a *lot* of them for parsers supporting it (e.g. the C and C++ one, which is the main default target of the …
=> Fix handling of locals

vimode/src/backends/backend-viw.c
This is just a binary for testing and the missing icons don't matter.
=> vimode: eliminate a warning

geanyctags/src/geanyctags.c
With a fallback on older glib versions.
=> geanyctags: Use g_pattern_spec_match_string() instead of g_pattern_match_string()

projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-utils.c, projectorganizer/src/prjorg-utils.h
Eliminates a warning on newer glib versions. Adds a fallback on older versions.
=> projectorganizer: Use g_pattern_spec_match_string() instead of g_pattern_match_string()

markdown/src/viewer.c
This PR modifies `replace_all` to avoid the infinite loop.  In each iteration, `replace_all` searches for `needle` starting from the beginning of `haystack`.  If `replacement` contains `needle`, the result is an infinite loop.  To prevent this from happening, `replace_all` should continue searching for `needle` from the end of the previous `replacement`.
Squashed and rebased from  #1128.  Resolves #936.
=> Markdown: Modify replace_all to avoid infinite loop

.github/workflows/build.yml
Instead of using a dated version of "cppcheck" from the runner image, we download the latest release of "cppcheck" and build it.
As building it takes a few minutes, the build result is cached to be re-used in succeeding build runs.
This should make us aware of failed checks in recent "cppcheck" versions quicker. Currently we notice these mostly only when running "make check" locally or when the nightly builds for Debian Unstable fail because they also use recent "cppcheck" versions.
Currently the build fails because of the pending changes in #1309, once this is merged, the build should succeed.
=> CI: Download, compile and use latest cppcheck version

latex/src/latexenvironments.c, latex/src/latexutils.c, latex/src/latexutils.h
This MR migrates the feature to insert any environment over to Geany's snippets workflow. Hence we don't need to bother about indention, like breaks etc. this much anymore. Also due to the cursor-feature it ensures to position the cursor at the right place , independent from the line break, indention etc. 
Due to this rework it makes the code also a little more readable and fixes #1071
=> LaTeX: Switch handling of insert (list) environments over to snippets workflow

.github/workflows/build.yml, addons/src/ao_tasks.c, build/cppcheck-geany-plugins.cfg, build/cppcheck.mk, geanyctags/src/geanyctags.c, geanygendoc/src/ggd-options.c, geanyprj/src/Makefile.am, geanyprj/src/utils.c, geniuspaste/src/geniuspaste.c, git-changebar/src/gcb-plugin.c, markdown/src/conf.c, scope/src/Makefile.am, scope/src/debug.c, treebrowser/src/Makefile.am, treebrowser/src/treebrowser.c, vimode/src/cmd-runner.c, workbench/src/sidebar.c, workbench/src/wb_project.c, workbench/src/workbench.c
Let's try to make cppcheck work again, and even report useful stuff.
During the journey it found a few actual issues, which is good.  It also found some false-positives, which isn't so good.
We probably could reduce the false positives by not using `--library=gtk`, but that also would reduce the actual issues it can find.
There are a few issues that should be reported upstream, but it's harder than it looks… if I could only remember my password on their tracker :confused: 
Anyway, what do you guys think?  Is it good?  Are there too many false-positives?  Should the suppressions be moved back to `AM_CPPCHECKFLAG`s not to alter the code, although it makes it harder to maintain?
=> Enhance cppcheck usage, fix CI and fix reported errors

geanyctags/README, projectorganizer/README, projectorganizer/src/prjorg-main.c, vimode/README, vimode/src/backends/backend-geany.c
1. Suggest using Github for reporting bugs and pull requests instead of sending them by email.
2. Use https:// instead of http://
3. Mention universal-ctags as a maintained version of ctags in geanyctags README
=> geanyctags, projectorganizer, vimode: Some README and URL updates

codenav/src/goto_file.c
Hi, this PR fixes a use-after-free in codenav's go-to-file. (which often results in a crash)
1. Run geany from command line, to observe error messages
2. Enable codenav plugin, open some document (to allow use of go-to tool)
3. Trigger go-to-file tool (e.g. via shortcut)
4. Write `/`
5. Cancel & close dialog
6. Trigger go-to-file again
7. Write `a`
-> You will likely see an assertion fail in the output, or if you are lucky geany will crash altogether:
`gtk_entry_completion_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed`
Valgrind shows an invalid read to previously freed memory:
<details>
```
Invalid read of size 8
at 0x4DD5820: UnknownInlinedFun (gtkentrycompletion.c:1224)
by 0x4DD5820: gtk_entry_completion_set_model (gtkentrycompletion.c:1220)
by 0xE2E89F3: …
```
=> codenav/goto_file: Fix use-after-free crash

vimode/src/cmd-runner.c, vimode/src/cmds/motion.c, vimode/src/excmd-runner.c, vimode/src/utils.c, vimode/src/utils.h
This PR addresses some issues of the plugin with folded lines - see the individual commits.
I'd also like to automatically set the cursor position when a block gets folded to be set on the visible line (and not hidden somewhere inside the fold) but right now I don't know how to correctly react to the fold events - see https://sourceforge.net/p/scintilla/bugs/2438/
@scresto09 Do the changes look OK to you and does the plugin behave correctly with them?
=> vimode: Handle folded lines correctly

vimode/src/Makefile.am, vimode/src/cmds/edit.c, vimode/src/cmds/excmds.c, vimode/src/cmds/undo.c, vimode/src/cmds/undo.h, vimode/src/context.h, vimode/src/utils.c, vimode/src/vi.c
Trying to get more Vim-like behavior for cursor position after using undo (U key)
=> Vimode: fix cursor position after using undo

projectorganizer/src/prjorg-project.c, workbench/src/tm_control.c
For some reason, since the latest MSYS2 update on my Windows system, I got compiler errors that `g_stat()` requires a `GStatBuf` type as second argument.
According to the docs, https://docs.gtk.org/glib/func.stat.html, this is correct and in Geany we also use `GStatBuf` in all places.
=> ProjectOrganizer, Workbench: Use GStatBuf for "g_stat()" calls

projectorganizer/src/prjorg-sidebar.c
This is a preparation in case https://github.com/geany/geany/pull/3861 gets merged in Geany.
=> projectorganizer: Use GtkFileChooserNative when configured in Geany

geanylua/glspi_app.c, geanylua/glspi_dlg.c, geanylua/glspi_doc.c, geanylua/glspi_init.c, geanylua/glspi_kfile.c, geanylua/glspi_run.c, geanylua/glspi_sci.c, geanylua/gsdlg_lua.c
The real name of the struct in Lua 5.1 is luaL_Reg.  Lua 5.1 contains a define for compatibility, but it is not present in LuaJIT or later 5.x releases.
=> GeanyLua: Use luaL_Reg instead of luaL_reg

addons/src/ao_systray.c
This avoids showing the status icon without an icon on startup and even if it is disabled while Geany is starting.
=> Addons: Hide status icon on startup until Geany has started

build/geany-plugins.nsi
If no explicit installation directory was specified and an existing, Geany installation was found, then use its installation directory.
Closes #1321.
=> Windows installer: Prefer Geany installation directory over user's HOME

geniuspaste/TODO, geniuspaste/src/geniuspaste.c
The pasted data might contain sensitive information and the pastebin service might be public and might not allow deleting a paste (at least not in a way the plugin supports).  Thus, ask confirmation by default in case the user accidentally triggered the action.
@xiota does this make you a tad more comfortable?  The UI isn't stellar, but it gets the job done and fearless users can disable it.
=> geniuspaste: Ask confirmation before pasting

build/updatechecker.m4, updatechecker/README, updatechecker/src/updatechecker.c
Port to libsoup3 (see https://github.com/geany/geany-plugins/pull/1295#issuecomment-1906999722 @jbicha) plus a couple other fixes I just couldn't leave there after seeing them :slightly_smiling_face: 
**:warning: DISCLAIMER:** I don't know neither libsoup2.4 nor libsoup3.  This is a uneducated guess by looking at [the scarce documentation](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html) and the API reference.  And it seems to work with limited testing (I tested manually only, for the normal case, the 404 case and the incorrect domain case -- all of which got the expected result).
=> updatechecker: Port to libsoup3 and small other fixes

geanylua/glspi_dlg.c
See issues [690](https://github.com/geany/geany-plugins/issues/690), [1374](https://github.com/geany/geany-plugins/issues/1374).
=> FIX: GeanyLua: 'Choose' dialog size/appearance (b4n's patch)

.editorconfig
See the related discussion in https://github.com/geany/geany/pull/1193.
The branch with this commit is here
https://github.com/techee/geany-plugins/tree/editorconfig
so the effect of this PR can be examined by browsing the code there.
=> Add .editorconfig so github uses the correct tab size (4)

vimode/src/cmds/special.c
The crosshatch (#) and asterisk (*) commands in Vim perform exact word searches. For example, with the cursor on "word", the asterisk would perform "/\\<word\\>" to search for the next exact occurrence of "word".
=> Surround word with "\\<" and "\\>" for search_current().

build/cppcheck-geany-plugins.suppressions, build/cppcheck.mk
This produces too many false-positives with GLib code.
See https://github.com/danmar/cppcheck/pull/7068 and https://github.com/danmar/cppcheck/pull/7390.
Closes #1417.
=> cppcheck: Disable nullPointerOutOfMemory check

geanylua/docs/geanylua-ref.html, geanylua/glspi_doc.c
=> GeanyLua: Fix geany.activate()

git-changebar/src/gcb-plugin.c
C23 is adding a bool keyword:
https://en.cppreference.com/w/c/keyword/bool
With GCC 15 (in development, bug fixing) this causes a failure: `error: expected identifier or '(' before 'bool'`
=> git-changebar: Rename bool for C23 compatibility

geanyctags/src/geanyctags.c
When activating the "Find Tag Declaration" menu item the line number in a new document was saved as a position to navigate back. We should save the same line number in the old document.
=> geanyctags: Fix navigation queue

geanyctags/src/readtags.c
The variable is not initialized, but it's not used there, and will be initialized farther down through an init call.
---
This is with 2.10 from Debian Bookworm.  2.14 and above seem to be smarter, so maybe we don't care about that.
If we do care, we could alternatively add a suppression in the Makefile.am, but that's a bit more fragile and risk getting forgotten. OTOH, this being a copied file, it might get forgotten on next update, although it might not be relevant anymore -- either by being changed or by being "fixed":
```diff
diff --git a/geanyctags/src/Makefile.am b/geanyctags/src/Makefile.am
index ffd38a8c..e908e2cf 100644
--- a/geanyctags/src/Makefile.am
+++ b/geanyctags/src/Makefile.am
@@ -13,4 +13,6 @@ geanyctags_la_CPPFLAGS = $(AM_CPPFLAGS) \
geanyctags_la_CFLAGS = $(AM_CFLAGS) …
```
=> geanyctags: Suppress a cppcheck warning

workbench/src/wb_monitor.c
When a monitored file or directory is removed, we call the handler for that event directly.  However, this might lead to removing our own monitoring entry, which means we must not reference it any further after having called the handler.
Fixes #1430.
=> workbench: Fix crash when a monitored entry is removed

lsp/src/lsp-sync.c
At least clangd discards the file if the range doesn't match what it sees, so this has the effect of breaking the LSP features whenever one type a multi-byte character.
---
:warning: beware, this has been barely tested.
I am moderately certain the fix is correct as it's the unit other pieces of the code use, but I didn't check whether the protocol actually expects -- but it seems to work with single-code-point character (I e.g. didn't try anything that would not have the same number of code units than code points).
To reproduce it's easy for me; just type anything non-latin.  E.g. I mistyped `streaù` instead of `stream` (`ù` is next to `m` on a French layout), and suddenly even basic completion or calltips stopped working in that file.
I found this error:
```
E[00:10:36.198] Failed to …
```
=> lsp: Fix incremental synchronization with multi-byte characters

lsp/src/lsp-main.c
There are already keybindings for standard Geany goto definition/declaration that will get propagated to the LSP server so there is not a real need for another pair of keybindings doing nearly the same. This is confusing for users (see https://github.com/techee/geany-lsp/discussions/79).
The only exception when this could get useful is when users configure the plugin not to use LSP for goto in which case standard Geany goto is used when using Geany goto definition/declaration. In this case, the extra keybinding would still use LSP features and users could choose between the two by using two different keybindings. However, such as feature is hard to discover and probably not used by many and better to make the UI less confusing for users.
@frlan @b4n This patch removes 2 translatable …
=> LSP: Remove keybindings for goto definition/declaration

geanylua/docs/geanylua-ref.html, geanylua/glspi_doc.c
From [discussion 4174](https://github.com/geany/geany/discussions/4174).
It's really strange: we have information about multi-line comments, but no single-line comments. Let's fix this :)
=> GeanyLua: geany.fileinfo: Added a field for single-line comments; all 'comment' fields are renamed as in filetype definition files.

markdown/src/plugin.c, webhelper/src/gwh-browser.c, webhelper/src/gwh-plugin.c, webhelper/src/gwh-plugin.h
Fixes #1447.
See https://github.com/geany/geany-plugins/issues/1447#issuecomment-2998133668, but basically apparently nowadays simply *loading* a webkit-using plugin means it cannot ever be unloaded, or else :boom:.
So, port both webkit-using plugins to the new plugin API (`geany_load_module()`) to be able to make the plugin resident also when it was only loaded for gathering information in the plugin dialog.
To reproduce the crashes (for me):
* install WebHelper and/or Markdown
* open the plugin manager, and *do not enable either plugins*
* close the plugin manager, and mind your own business for a few seconds (I typically tried the open dialog, but anything works, and probably doing nothing as well)
* :boom: with a weird backtrace
Workarounds:
* not having a webkit-using plugin …
=> Fix crash with unloaded WebKit-using plugins

geanynumberedbookmarks/src/geanynumberedbookmarks.c
Inside `plugin_init()`, the current version precomputes key values for number keys after pressing shift (on US keyboard, `!` for `1`, `@`, for `2`, etc.) and uses these values for detecting key presses. However, it makes some assumptions that are not quite correct for all keyboard layouts:
1. It assumes that keyboard layout cannot change and precomputes key values once on plugin init. It is quite common to change keyboard layout while using an editor and the precomputed values aren't correct in this case.
2. It assumes that numbers are typed directly for all keyboard layouts without pressing shift. This is incorrect e.g. for the Czech keyboard where numbers are typed by Shift plus a key from the top row. In this case the current code doesn't precompute Shift+key values correctly
3. By …
=> numberedbookmarks: fix Ctrl+num and Ctrl+Shift+num on various keyboard layouts

COPYING.md, README, addons/README, autoclose/README, automark/README, codenav/README, debugger/README, defineformat/README, geanylua/README, geanyvc/README, latex/README, markdown/README, overview/COPYING, spellcheck/README, treebrowser/COPYING, treebrowser/README
As discusssed in https://github.com/geany/geany/pull/4371.
Also added a license note to a few plugin READMEs where it was missing and added `COPYING` files with the full license text for Overview and TreeBrowser.
I tried to find the correct license for the plugins by checking their `COPYING` file, then `README` file and if still unsure then checked the source code.
I might have missed something.
=> Add COPYING file for all included plugins

vimode/src/cmd-params.c, vimode/src/cmd-params.h, vimode/src/cmd-runner.c, vimode/src/cmds/changemode.c, vimode/src/cmds/excmds.c
Fixes handling of `b`/`B`/`%` when used together with e.g. `d`.
Fixes https://github.com/geany/geany-plugins/issues/1487
=> vimode: Various fixes related to various motion commands
