geany/geany-plugins

build/multiterm.m4, build/vala.m4
=> Autotools Vala checks

git-changebar/README, git-changebar/src/gcb-plugin.c
@techee here you go ;)  https://github.com/geany/geany-plugins/pull/189#issuecomment-75032954
=> git-changebar: Add keybindings to navigate through hunks

build/wafutils.py, git-changebar/wscript_build
Also use the new feature to fix *git-changebar* plugin name and installation directory for common files.
=> Waf: Allow to explicitly set plugin name

HACKING
re comments on https://github.com/geany/geany-plugins/commit/8eb982704c21d5052a90b05c5bcfb1c3a8ff6b8f#diff-884b897f0b13c2d7044127cda8920c82R118
=> Fix redundancy and typos in HACKING

pairtaghighlighter/ChangeLog
Please, merge this before release 1.25.
=> PairTagHighlighter / Update ChangeLog

po/de.po
=> Fix typos in German translation

tableconvert/src/tableconvert_ui.c
Not tested but straightforward
=> tableconvert: Drop use of the most obvious deprecated Geany API

scope/src/Makefile.am
http://trac.cppcheck.net/ticket/7243
=> scope: Ignore a false positive from cppcheck

pairtaghighlighter/src/pair_tag_highlighter.c
Not really tested.
@vmkononenko
=> pairtaghighlighter: Drop use of the most obvious deprecated Geany API

markdown/src/Makefile.am, markdown/src/plugin.c
=> markdown: Remove an unused define

build/geanylatex.m4, build/geanymacro.m4, build/geanynumberedbookmarks.m4, build/geanyprj.m4, geanylatex/src/bibtex.c, geanylatex/src/geanylatex.c, geanylatex/src/latexenvironments.c, geanylatex/src/reftex.c, geanylatex/src/templates.c, geanymacro/src/geanymacro.c, geanynumberedbookmarks/src/geanynumberedbookmarks.c, geanyprj/src/menu.c
Geany requires GTK+ 2.24 minimum, so all the used APIs are there directly.
=> GTK+3 support for more plugins

pretty-printer/Makefile.am
=> pretty-printer: Fix wrong plugin name in Makefile.am

geanydoc/src/geanydoc.c
=> geanydoc: Drop use of the most obvious deprecated Geany API

codenav/src/codenavigation.c, codenav/src/codenavigation.h
Not tested, but builds fine.
@federeghe
=> Codenav: Remove obvious deprecated code

geanylua/glspi_doc.c, geanylua/glspi_sci.c
Not really tested, but pretty straightforward.
=> geanylua: Drop use of the most obvious deprecated Geany API

pretty-printer/src/PluginEntry.c, pretty-printer/src/PrettyPrinter.c, pretty-printer/src/PrettyPrinter.h
=> Pretty printer: Geany deprecated stuff fixes and other stuff

geanylipsum/src/geanylipsum.c
=> geanylipsum: Add ellipsis to menu item requiring further user input

git-changebar/README, multiterm/README, pohelper/README
=> Fix three plugin names in their READMEs

po/fr.po
=> Fix typo in French translation

commander/src/commander-plugin.c
Add keybindings triggering the command panel and ensuring a default prefix, making it easier to select only commands or files without having to manually type the prefix.
=> commander: Add keybindings for triggering a particular filter type

geanygendoc/README
=> geanygendoc: Fix three typos in README

spellcheck/src/speller.c
=> spellcheck: Fix memory leak on duplicate dictionaries

git-changebar/src/gcb-plugin.c
Properly restore the BOM in the document buffer before diffing it against the Git buffer, not to diff the missing BOM.
Fixes #482.
=> git-changebar: Fix handling of documents with a Unicode BOM

MAINTAINERS
As discussed with b4n on IRC, we need a maintainer for the geanyprj plugin. Yurand hasn't responded in 9 days, so this is my bid to take over maintainership "for odd fixes".
=> new maintainer for plugin geanyprj

markdown/src/viewer.c
Stop using a phony base URI and create one from the current filename, with various fallbacks in case the file isn't saved yet or URI encoding fails.
Closes #500
=> Markdown: Fix relative paths

tableconvert/README
Make the SQL-output a line block as of
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#line-blocks
=> Improve the README for tableconvert plugin

automark/src/automark.c
=> automark: Replace deprecated sci_get_text_range()

geanylua/geanylua.c, geanylua/glspi.h, geanylua/glspi_init.c, geanylua/gsdlg.c
Untested and don't know much what I'm doing - ideal combination :-).
=> geanylua: Remove deprecated GeanyFunctions

lineoperations/ChangeLog, lineoperations/README, lineoperations/src/linefunctions.c, lineoperations/src/linefunctions.h, lineoperations/src/lineoperations.c
Here are some changes to lineoperations; adding selection support.
If a selection is made in the file, the line operation will be applied to the lines within the selection, rather than the whole file.
Like usual, I'm open to hear any suggestions/improvements.
=> lineoperations: added selection support

projectorganizer/src/prjorg-sidebar.c
=> projectorganizer: Remember expanded directories in the sidebar when reloading

po/es.po
Also fixed some others wrong translations.
=> Updated spanish translation for 1.30

projectorganizer/src/prjorg-sidebar.c
Reverts geany/geany-plugins#555
=> Revert "projectorganizer: Make sure project is open before trying to expand the tree"

lineoperations/README, lineoperations/src/linefunctions.c, lineoperations/src/linefunctions.h, lineoperations/src/lineoperations.c
Adds the requested feature from issue #516 of keeping only unique lines in the Line Operation plugin
=> Add Keep Unique Lines feature resolves #516

automark/README
Just added some more documentation.
=> automark: extended README. Closes #492.

geanylua/glspi_app.c, geanylua/gsdlg.c
=> geanylua: Replace deprecated tm_get_real_path().

workbench/src/plugin_main.c, workbench/src/wb_project.c
=> Workbench: fixed not closed file handles on directory scanning (thanks to techee). Fixes #607.

MAINTAINERS
I'd like to maintain the treebrowser plugin once again (I was also the maintainer for a while a few years ago before I got too busy with work and had to resign).  I'm interested in fixing various bugs and making it as reliable as the rest of Geany.
=> treebrowser: Add myself as maintainer

workbench/src/popup_menu.c, workbench/src/sidebar.c, workbench/src/sidebar.h, workbench/src/utils.c, workbench/src/utils.h
This change adds a feature which enables the user to open/close all files
of the selected project, directory or folder. The feature can be accessed by
using the context menu of the workbench sidebar.
=> workbench: Added "open/close all files" feature

workbench/src/utils.c
=> Remove some unused variables and initialize some

NEWS
=> Correct Workbench PR# in NEWS

workbench/src/dialogs.c, workbench/src/sidebar.c
See individual commits for details
=> Various small fixes for the Workbench plugin

spellcheck/src/scplugin.c
To do so, we need to always save the config file on plugin
cleanup/shutdown and move the configuration save logic to
its own function.
Closes #667.
=> SpellCheck: Remember 'Check while typing' setting between sessions

addons/README
I updated the README file to describe the new features implemented in PR #664.
=> addons: updated README. See PR #664.

pohelper/src/gph-plugin.c
As usual, closing in to a release calls for updating the translations and thus using the plugin, leading to finding issues and shortcomings.  Here are various fixes and improvements for this iteration. Some are actual bug fixes (089786be21422e25c5122d86e0b8b98ffb36798c), some are safety (9059b5505a359627fe79124a5f7ebc6c6776f0b1 and cdaa961ce6b441162d4f6bcb329d0307d8945e01), and some are improvements (2fb4dd080ad9cd521f9b5d981c517314fd3c6b7c, e1175d4c0e32f9b76e0f440abd9e657369d405eb, f76f801ce19bb24b70b4fd424498a408dec20d67, cff154c3ba7aac703ae1bcd901a1177252934051).
=> pohelper: Various fixes and improvements

build/treebrowser.m4, treebrowser/src/treebrowser.c
=> treebrowser: removed HAVE_GIO checks

MAINTAINERS, scope/src/scope.c
As mentioned earlier I use the scope plugin from time to time and I would be willing to become the maintainer. I'll try my best to keep it alive.
=> scope: new-maintainer: LarsGit223

treebrowser/src/treebrowser.c
=> treebrowser: changed confusing function names

build/spellcheck.m4
=> Spellcheck: support new "enchant-2" package name

geanyctags/src/geanyctags.c
When prj->base_path is relative, construct path using prj->file_name
so base path is relative to the project file directory.
Fixes #698
=> geanyctags: Use base path as relative to the project file path

vimode/src/cmds/motion.c
This is a sister implementation for "k" in order to behave like "j" when wrapping is on (see #748). The problem with the current implementation is that "k" moves caret to the last line of a wrapped line instead of the first one like "j".
@pcworld Can you check if it looks good to you? This one is a bit more complex because one has to either "iterate" over the wraps when going up (for the first line only) or go to the previous line and go down.
=> vimode: When wrapping is on, "k" should go to the first line of wrapping

latex/README
Closes https://github.com/geany/plugins.geany.org/issues/8
=> Update link to geany latex plugin docs

.travis.yml, utils/src/Makefile.am
Here again, I'll let it kick in, fix the issue (as there's one with distcheck right now) and then only should it be merged.  The goal is to make sure everything's working as it should.
=> travis: Run distcheck as well

README
Also remove "cppcheck" and "extra-c-warnings" which are rather
./configure options than plugins.
=> Add "vimode" plugin to README

projectorganizer/src/prjorg-project.c, projectorganizer/src/prjorg-project.h, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-utils.c, projectorganizer/src/prjorg-utils.h
This pull request adds some patches on top of #767 and deprecates the original pull request.
@frlan If it looks OK to you, would you please merge it?
=>  Add file operations to Project Organizer v2

autoclose/src/autoclose.c
=> autoclose: use new plugin API

codenav/src/codenavigation.c
=> codenav: use new plugin API.

debugger/src/plugin.c
=> debugger: use new plugin API

devhelp/src/dhp-plugin.c, devhelp/src/dhp-plugin.h
=> devhelp: use new plugin API

vimode/src/excmd-prompt.c
The history is created only for the Geany session and unlike vim, isn't
persisted after Geany re-launch.
Fixes #846
=> vimode: Allow browsing ex command history using arrows

workbench/README
=> workbench: added short history to README

addons/src/addons.c, addons/src/ao_blanklines.c, addons/src/ao_colortip.c, addons/src/ao_markword.c, addons/src/ao_systray.c, debugger/src/breakpoints.c, debugger/src/callbacks.h, debugger/src/dpaned.c, debugger/src/markers.c, debugger/src/markers.h, debugger/src/tpage.c, geanydoc/src/config.c, geanydoc/src/geanydoc.c, geanyextrasel/src/extrasel.c, geanyinsertnum/src/insertnum.c, geanylua/gsdlg.c, geanynumberedbookmarks/src/geanynumberedbookmarks.c, geanyprj/src/geanyprj.h, keyrecord/src/keyrecord.c, lineoperations/src/linefunctions.h, lineoperations/src/lineoperations.c, scope/src/common.h, scope/src/plugme.c, treebrowser/src/treebrowser.c
=> Cleanup: fixed usage of '#include "geanyplugin.h"'

NEWS
I added two missing points and fixed two little typos.
=> NEWS: two additions and two fixed typos

autoclose/src/autoclose.c
Using ```Shift```+```Backspace``` at the moment only removes round, square, waved and angle brackets but not quotes. With this PR the feature also works for single, double and back-quotes. Closes #687.
=> autoclose: remove pairing quotes

geanyprj/src/sidebar.c
=> geanyprj: fixed cut-off sidebar tab under gtk3

vimode/src/cmds/changemode.c
=> vimode: Make o/O respect auto indentation

codenav/src/codenavigation.h
**Warning**: This depends on https://github.com/geany/geany/pull/2309 being merged.
=> g_print: Add newline now Geany's g_print handler doesn't

projectorganizer/src/prjorg-project.c
Since the base path can change when the project dialog is open, we must
re-read the base path, otherwise it doesn't get updated.
Fixes #901
=> projectorganizer: re-read base path when updating project

latex/src/latex.c
This adds the feature requested in #950 to respect the user preference for line indentation. This is my first contribution to this project, so feel free to review and give feedback :)
=> latex: added feature: indent line in new environment (fixes #950)

geanyvc/README, geanyvc/src/Makefile.am, geanyvc/src/geanyvc.c, geanyvc/src/unittests.c, geanyvc/src/vc_fossil.c, po/POTFILES.in, po/be.po, po/ca.po, po/da.po, po/de.po, po/el.po, po/es.po, po/fr.po, po/gl.po, po/it.po, po/ja.po, po/kk.po, po/nl.po, po/pt.po, po/pt_BR.po, po/ru.po, po/tr.po, po/zh_CN.po
=> GeanyVC: Add support for Fossil SCM (fossil-scm.org)

geanyvc/src/geanyvc.c
This comes in handy to quickly select and deselect single files in
the commit dialog.
=> GeanyVC: Allow to toggle single files with Space and Return keys

addons/README, addons/src/ao_colortip.c
I added a second alternative size for the color calltip. I also added documentation about the alternative sizes in the README file.
=> Additional Improvements to the Color Calltip

spellcheck/README
Progress towards https://github.com/geany/geany/issues/2508
=> Add link to how to install, fix some English

geanyvc/src/geanyvc.c
=> GeanyVC: Show ellipsis in menu items requiring further user input

po/be.po, po/ca.po, po/da.po, po/de.po, po/el.po, po/es.po, po/fr.po, po/gl.po, po/it.po, po/ja.po, po/kk.po, po/nl.po, po/pt.po, po/pt_BR.po, po/ru.po, po/tr.po, po/zh_CN.po
Update po-files related to #1029, part of fix for #251 .
=> GeanyVC: Show ellipsis in menu items requiring further user input (po update)

geanyvc/src/geanyvc.c
=> GeanyVC: Correct the displaying of tooltip for the attach to menubar action

po/uk.po
Fixes #1045 . Covers UI messages for all 45 of the current plugins, reviewed and cross-checked.
By the way, this turned out to be a curious way to catch some existing issues/quirks with current plugins. Likely most of these issues have been logged by users already.
=> PO: Add Ukrainian translation

.travis.yml
And remove now obsolete self built libgit2.
=> Use Ubuntu Bionic for Travis builds

vimode/src/cmds/edit.c
This patch adds \n if it's missing at the EOF before line operations
like yank, delete or paste are parformed to make sure these operations
always work the same way. If added, the extra \n is removed from the
file when the operation is completed.
Fixes the part of #1060 related to line yanking.
=> vimode: fix line operation problems when NL is missing at EOF

geanyctags/src/geanyctags.c, geanyctags/src/readtags.c, geanyctags/src/readtags.h
=> Geany ctags fixes

geanyvc/src/geanyvc.c, geanyvc/src/vc_git.c
=> GeanyVC: Report a completion status of the commit command

po/es.po
Updated Spanish translation of plugins for 1.38
=> Updated plugins es.po for 1.38

build/geany-plugins.nsi, build/gtk-bundle-from-msys2.sh
Part of https://github.com/geany/geany/issues/3063.
Do not merge before https://github.com/geany/geany/pull/3082 is merged.
=> Windows: libxml2 is now bundled in Geany itself

build/geany-plugins.nsi, build/gtk-bundle-from-msys2.sh
Followup of https://github.com/geany/geany/pull/3082 and https://github.com/geany/geany-plugins/pull/1151.
=> Windows: xz is now bundled in Geany itself

geanyvc/src/geanyvc.c, geanyvc/src/geanyvc.h
=> GeanyVC: Support the use of external diff-tool in directory context

po/uk.po
Updated Ukrainian translations of several messages; also updated the source file references.
=> po: Update Ukrainian translation

treebrowser/src/treebrowser.c
Port "Open Externally" and "Open in terminal" actions to the spawn API
for better support on Windows.
Also remove unnecessary hard-coded "cmd" command on Windows and use the
configured command instead.
Closes #556.
=> TreeBrowser: Port spawning external commands to the spawn API

treebrowser/src/treebrowser.c
=> TreeBrowser: Fix refresh from popup menu with a selected file

po/es.po
Updated Spanish translation of the plugins for version 2.0
=> Update es.po for version 2.0

lineoperations/src/lineoperations.c, lineoperations/src/lo_fns.c, lineoperations/src/lo_prefs.c
@smostertdev @frlan This makes translations actually work in several places (prefs dialog, keybindings list, Nth line dialog)
=> lineoperations: Fix translation of some strings

build/version-bump
It's pretty much the same as in Geany, without codename and for the G-P relevant files.
=> Add version-bump script

lineoperations/src/lo_prefs.c
=> lineoperations: Removed debug code (fixes #1322)

MAINTAINERS
Request to adopt and change status to Odd Fixes in hopes of facilitating bug fix commits.
Open to comaintaining, if other user is interested.  (@Skif-off?)
If adoption is successful, would...
* Review [#1234](https://github.com/geany/geany-plugins/pull/1234) / [#1229](https://github.com/geany/geany-plugins/pull/1229) to ensure it's still needed and functions as expected.
* Attempt to confirm [#1374](https://github.com/geany/geany-plugins/pull/1374) and whether patch in comment should be added.
* Look for other known problems and fixes.
=> GeanyLua: Adopt and change status to Odd Fixes

build/gtk-bundle-from-msys2.sh
Newer Wine versions require the extension.
Relates to
https://github.com/geany/geany/pull/4088 and
https://github.com/geany/infrastructure/pull/12.
=> Windows: Add ".exe" suffix to post install commands

geanynumberedbookmarks/README, geanynumberedbookmarks/src/geanynumberedbookmarks.c
Additional options for numberedbookmarks
1. Always save bookmarks, even if file has not changed
2. Always try to load bookmarks, even if file has changed
=> numberedbookmarks additional options

po/POTFILES.in, projectorganizer/src/prjorg-main.c, projectorganizer/src/prjorg-menu.c, projectorganizer/src/prjorg-project.h, projectorganizer/src/prjorg-sidebar.c, projectorganizer/src/prjorg-sidebar.h, projectorganizer/src/prjorg-utils.c, projectorganizer/src/prjorg-utils.h
=> projectorganizer: Add preferences for open file manager and terminal commands

lsp/src/lsp-main.c
If a project is open at the time when the plugin is loaded from the plugin manager, we need to manually read its contents otherwise we miss settings specified in the project file (which is normally loaded in the project-open signal but it was called before the plugin was loaded).
Hopefully the right way to fix the issue described in https://github.com/geany/geany-plugins/pull/1443.
=> LSP: Load project settings when plugin initialized

codenav/src/codenavigation.c
=> codenav: Fix crash caused by missing NULL check

lsp/src/lsp-command.c, lsp/src/lsp-command.h
See https://github.com/techee/geany-lsp/issues/81.
=> LSP: fix codeAction/resolve

vimode/src/cmds/motion.c
Fixes https://github.com/geany/geany-plugins/issues/1482
=> vimode: make f/F/t/T case sensitive

spellcheck/src/speller.c
See #1492.
The second commit can be removed if wanted, it's not currently necessary.
=> spellcheck: Fix wordchars restoration
